-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2017.4
-- Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity dqo_2_abc is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    d_V : IN STD_LOGIC_VECTOR (24 downto 0);
    q_V : IN STD_LOGIC_VECTOR (24 downto 0);
    theta_V : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (24 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (24 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (24 downto 0) );
end;


architecture behav of dqo_2_abc is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv17_1FBD0 : STD_LOGIC_VECTOR (16 downto 0) := "11111101111010000";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv16_FBD0 : STD_LOGIC_VECTOR (15 downto 0) := "1111101111010000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv16_7FFF : STD_LOGIC_VECTOR (15 downto 0) := "0111111111111111";
    constant ap_const_lv16_8000 : STD_LOGIC_VECTOR (15 downto 0) := "1000000000000000";
    constant ap_const_lv17_430 : STD_LOGIC_VECTOR (16 downto 0) := "00000010000110000";
    constant ap_const_lv16_430 : STD_LOGIC_VECTOR (15 downto 0) := "0000010000110000";
    constant ap_const_lv32_29 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101001";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_25 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100101";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv32_26 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100110";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv25_FFFFFF : STD_LOGIC_VECTOR (24 downto 0) := "0111111111111111111111111";
    constant ap_const_lv25_1000000 : STD_LOGIC_VECTOR (24 downto 0) := "1000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal this_assign_1_fu_234_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal this_assign_1_reg_1251 : STD_LOGIC_VECTOR (15 downto 0);
    signal this_assign_11_1_fu_254_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal this_assign_11_1_reg_1256 : STD_LOGIC_VECTOR (15 downto 0);
    signal this_assign_12_1_fu_342_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal this_assign_12_1_reg_1261 : STD_LOGIC_VECTOR (15 downto 0);
    signal this_assign_13_1_fu_362_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal this_assign_13_1_reg_1266 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_calc_sin_cos_fu_96_ap_return : STD_LOGIC_VECTOR (15 downto 0);
    signal p_s_reg_1271 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_calc_sin_cos_fu_96_ap_done : STD_LOGIC;
    signal grp_calc_sin_cos_fu_105_ap_done : STD_LOGIC;
    signal grp_calc_sin_cos_fu_114_ap_done : STD_LOGIC;
    signal grp_calc_sin_cos_fu_123_ap_done : STD_LOGIC;
    signal grp_calc_sin_cos_fu_132_ap_done : STD_LOGIC;
    signal grp_calc_sin_cos_fu_141_ap_done : STD_LOGIC;
    signal ap_block_state3_on_subcall_done : BOOLEAN;
    signal grp_calc_sin_cos_fu_105_ap_return : STD_LOGIC_VECTOR (15 downto 0);
    signal p_1_reg_1276 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_calc_sin_cos_fu_114_ap_return : STD_LOGIC_VECTOR (15 downto 0);
    signal p_2_reg_1281 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_calc_sin_cos_fu_123_ap_return : STD_LOGIC_VECTOR (15 downto 0);
    signal p_3_reg_1286 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_calc_sin_cos_fu_132_ap_return : STD_LOGIC_VECTOR (15 downto 0);
    signal p_4_reg_1291 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_calc_sin_cos_fu_141_ap_return : STD_LOGIC_VECTOR (15 downto 0);
    signal p_0_reg_1296 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Val2_s_fu_1209_p2 : STD_LOGIC_VECTOR (40 downto 0);
    signal p_Val2_s_reg_1301 : STD_LOGIC_VECTOR (40 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal p_Val2_74_fu_1215_p2 : STD_LOGIC_VECTOR (40 downto 0);
    signal p_Val2_74_reg_1307 : STD_LOGIC_VECTOR (40 downto 0);
    signal p_Val2_80_fu_1221_p2 : STD_LOGIC_VECTOR (40 downto 0);
    signal p_Val2_80_reg_1313 : STD_LOGIC_VECTOR (40 downto 0);
    signal p_Val2_6_45_fu_1227_p2 : STD_LOGIC_VECTOR (40 downto 0);
    signal p_Val2_6_45_reg_1319 : STD_LOGIC_VECTOR (40 downto 0);
    signal p_Val2_86_fu_1233_p2 : STD_LOGIC_VECTOR (40 downto 0);
    signal p_Val2_86_reg_1325 : STD_LOGIC_VECTOR (40 downto 0);
    signal p_Val2_7_46_fu_1239_p2 : STD_LOGIC_VECTOR (40 downto 0);
    signal p_Val2_7_46_reg_1331 : STD_LOGIC_VECTOR (40 downto 0);
    signal tmp_fu_402_p2 : STD_LOGIC_VECTOR (40 downto 0);
    attribute use_dsp48 : string;
    attribute use_dsp48 of tmp_fu_402_p2 : signal is "no";
    signal tmp_reg_1337 : STD_LOGIC_VECTOR (40 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal signbit_reg_1342 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_77_fu_480_p2 : STD_LOGIC_VECTOR (24 downto 0);
    signal p_Val2_77_reg_1348 : STD_LOGIC_VECTOR (24 downto 0);
    signal newsignbit_fu_486_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal newsignbit_reg_1354 : STD_LOGIC_VECTOR (0 downto 0);
    signal carry_fu_500_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal carry_reg_1360 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range2_all_ones_fu_516_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range2_all_ones_reg_1367 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_ones_fu_532_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_ones_reg_1372 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_zeros_fu_538_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_zeros_reg_1379 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_15_fu_550_p2 : STD_LOGIC_VECTOR (40 downto 0);
    attribute use_dsp48 of tmp_15_fu_550_p2 : signal is "no";
    signal tmp_15_reg_1384 : STD_LOGIC_VECTOR (40 downto 0);
    signal signbit_11_reg_1389 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_83_fu_628_p2 : STD_LOGIC_VECTOR (24 downto 0);
    signal p_Val2_83_reg_1395 : STD_LOGIC_VECTOR (24 downto 0);
    signal newsignbit_19_fu_634_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal newsignbit_19_reg_1401 : STD_LOGIC_VECTOR (0 downto 0);
    signal carry_9_fu_648_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal carry_9_reg_1407 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range2_all_ones_7_fu_664_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range2_all_ones_7_reg_1414 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_ones_21_fu_680_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_ones_21_reg_1419 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_zeros_2_fu_686_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_zeros_2_reg_1426 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_24_fu_698_p2 : STD_LOGIC_VECTOR (40 downto 0);
    attribute use_dsp48 of tmp_24_fu_698_p2 : signal is "no";
    signal tmp_24_reg_1431 : STD_LOGIC_VECTOR (40 downto 0);
    signal signbit_12_reg_1436 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_89_fu_776_p2 : STD_LOGIC_VECTOR (24 downto 0);
    signal p_Val2_89_reg_1442 : STD_LOGIC_VECTOR (24 downto 0);
    signal newsignbit_21_fu_782_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal newsignbit_21_reg_1448 : STD_LOGIC_VECTOR (0 downto 0);
    signal carry_10_fu_796_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal carry_10_reg_1454 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range2_all_ones_8_fu_812_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range2_all_ones_8_reg_1461 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_ones_24_fu_828_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_ones_24_reg_1466 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_zeros_3_fu_834_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_zeros_3_reg_1473 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_calc_sin_cos_fu_96_ap_start : STD_LOGIC;
    signal grp_calc_sin_cos_fu_96_ap_idle : STD_LOGIC;
    signal grp_calc_sin_cos_fu_96_ap_ready : STD_LOGIC;
    signal grp_calc_sin_cos_fu_96_flag : STD_LOGIC;
    signal grp_calc_sin_cos_fu_105_ap_start : STD_LOGIC;
    signal grp_calc_sin_cos_fu_105_ap_idle : STD_LOGIC;
    signal grp_calc_sin_cos_fu_105_ap_ready : STD_LOGIC;
    signal grp_calc_sin_cos_fu_105_flag : STD_LOGIC;
    signal grp_calc_sin_cos_fu_114_ap_start : STD_LOGIC;
    signal grp_calc_sin_cos_fu_114_ap_idle : STD_LOGIC;
    signal grp_calc_sin_cos_fu_114_ap_ready : STD_LOGIC;
    signal grp_calc_sin_cos_fu_114_flag : STD_LOGIC;
    signal grp_calc_sin_cos_fu_123_ap_start : STD_LOGIC;
    signal grp_calc_sin_cos_fu_123_ap_idle : STD_LOGIC;
    signal grp_calc_sin_cos_fu_123_ap_ready : STD_LOGIC;
    signal grp_calc_sin_cos_fu_123_flag : STD_LOGIC;
    signal grp_calc_sin_cos_fu_132_ap_start : STD_LOGIC;
    signal grp_calc_sin_cos_fu_132_ap_idle : STD_LOGIC;
    signal grp_calc_sin_cos_fu_132_ap_ready : STD_LOGIC;
    signal grp_calc_sin_cos_fu_132_flag : STD_LOGIC;
    signal grp_calc_sin_cos_fu_141_ap_start : STD_LOGIC;
    signal grp_calc_sin_cos_fu_141_ap_idle : STD_LOGIC;
    signal grp_calc_sin_cos_fu_141_ap_ready : STD_LOGIC;
    signal grp_calc_sin_cos_fu_141_flag : STD_LOGIC;
    signal ap_reg_grp_calc_sin_cos_fu_96_ap_start : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_reg_grp_calc_sin_cos_fu_105_ap_start : STD_LOGIC := '0';
    signal ap_reg_grp_calc_sin_cos_fu_114_ap_start : STD_LOGIC := '0';
    signal ap_reg_grp_calc_sin_cos_fu_123_ap_start : STD_LOGIC := '0';
    signal ap_reg_grp_calc_sin_cos_fu_132_ap_start : STD_LOGIC := '0';
    signal ap_reg_grp_calc_sin_cos_fu_141_ap_start : STD_LOGIC := '0';
    signal tmp_82_fu_150_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal p_Val2_78_fu_154_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal p_Val2_79_fu_168_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal isneg_fu_160_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal newsignbit_18_fu_174_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_83_fu_182_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_84_fu_194_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge_i_i16_fu_206_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_18_fu_200_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge3_fu_212_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_98_mux_fu_218_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Val2_6_fu_226_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal overflow_14_fu_188_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge_i_i17_not_fu_242_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge4_fu_248_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_84_fu_262_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal p_Val2_85_fu_276_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal isneg_6_fu_268_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal newsignbit_20_fu_282_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_91_fu_290_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_92_fu_302_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge_i_i18_fu_314_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_20_fu_308_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge7_fu_320_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_105_mux_fu_326_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Val2_8_fu_334_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal overflow_16_fu_296_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge_i_i20_not_fu_350_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge8_fu_356_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_77_fu_399_p1 : STD_LOGIC_VECTOR (41 downto 0);
    signal tmp_s_fu_396_p1 : STD_LOGIC_VECTOR (41 downto 0);
    signal p_Val2_75_fu_406_p2 : STD_LOGIC_VECTOR (41 downto 0);
    signal tmp_147_fu_438_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_149_fu_456_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_fu_442_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_i_i_fu_464_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal qbit_fu_430_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal qb_assign_s_fu_470_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_76_fu_420_p4 : STD_LOGIC_VECTOR (24 downto 0);
    signal tmp_78_fu_476_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal tmp_148_fu_448_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_79_fu_494_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_13_fu_506_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_14_fu_522_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_86_fu_547_p1 : STD_LOGIC_VECTOR (41 downto 0);
    signal tmp_85_fu_544_p1 : STD_LOGIC_VECTOR (41 downto 0);
    signal p_Val2_81_fu_554_p2 : STD_LOGIC_VECTOR (41 downto 0);
    signal tmp_156_fu_586_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_158_fu_604_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_12_fu_590_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_i_i5_fu_612_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal qbit_12_fu_578_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal qb_assign_3_fu_618_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_82_fu_568_p4 : STD_LOGIC_VECTOR (24 downto 0);
    signal tmp_87_fu_624_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal tmp_157_fu_596_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_88_fu_642_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_22_fu_654_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_23_fu_670_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_94_fu_695_p1 : STD_LOGIC_VECTOR (41 downto 0);
    signal tmp_93_fu_692_p1 : STD_LOGIC_VECTOR (41 downto 0);
    signal p_Val2_87_fu_702_p2 : STD_LOGIC_VECTOR (41 downto 0);
    signal tmp_165_fu_734_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_167_fu_752_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_13_fu_738_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_i_i6_fu_760_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal qbit_13_fu_726_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal qb_assign_4_fu_766_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_88_fu_716_p4 : STD_LOGIC_VECTOR (24 downto 0);
    signal tmp_95_fu_772_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal tmp_166_fu_744_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_96_fu_790_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_31_fu_802_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_32_fu_818_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal tmp_151_fu_840_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_80_fu_852_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_41_i9_fu_858_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal deleted_zeros_fu_847_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_not_i3_fu_873_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge_i_fu_879_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_81_fu_884_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal deleted_ones_fu_863_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_38_i9_fu_869_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge40_demorgan_i_2_fu_895_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp1_demorgan_fu_900_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp1_fu_906_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_fu_912_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal overflow_fu_889_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp2_fu_923_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge_i_i_fu_917_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_not_fu_929_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_95_mux_fu_935_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal p_Val2_s_44_fu_942_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal tmp_160_fu_957_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_89_fu_969_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_41_i_fu_975_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal deleted_zeros_9_fu_964_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_not_i_fu_990_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge_i3_fu_996_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_90_fu_1001_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal deleted_ones_11_fu_980_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_38_i_fu_986_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge40_demorgan_i_fu_1012_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp3_demorgan_fu_1017_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp3_fu_1023_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_19_fu_1029_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal overflow_15_fu_1006_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp4_fu_1040_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge_i_i17_fu_1034_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_17_not_fu_1046_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_103_mux_fu_1052_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal p_Val2_7_fu_1059_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal tmp_169_fu_1074_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_97_fu_1086_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_41_i1_fu_1092_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal deleted_zeros_10_fu_1081_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_not_i4_fu_1107_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge_i4_fu_1113_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_98_fu_1118_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal deleted_ones_14_fu_1097_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_38_i1_fu_1103_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge40_demorgan_i_1_fu_1129_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp5_demorgan_fu_1134_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp5_fu_1140_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_21_fu_1146_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal overflow_17_fu_1123_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp6_fu_1157_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge_i_i19_fu_1151_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_19_not_fu_1163_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_110_mux_fu_1169_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal p_Val2_9_fu_1176_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal ssdm_int_V_write_ass_fu_949_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal ssdm_int_V_write_ass_1_fu_1066_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal ssdm_int_V_write_ass_2_fu_1183_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal p_Val2_s_fu_1209_p0 : STD_LOGIC_VECTOR (24 downto 0);
    signal OP2_V_fu_373_p1 : STD_LOGIC_VECTOR (40 downto 0);
    signal p_Val2_74_fu_1215_p0 : STD_LOGIC_VECTOR (24 downto 0);
    signal OP2_V_2_fu_380_p1 : STD_LOGIC_VECTOR (40 downto 0);
    signal p_Val2_80_fu_1221_p0 : STD_LOGIC_VECTOR (24 downto 0);
    signal p_Val2_6_45_fu_1227_p0 : STD_LOGIC_VECTOR (24 downto 0);
    signal p_Val2_86_fu_1233_p0 : STD_LOGIC_VECTOR (24 downto 0);
    signal p_Val2_7_46_fu_1239_p0 : STD_LOGIC_VECTOR (24 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);

    component calc_sin_cos IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        theta_aux_V : IN STD_LOGIC_VECTOR (15 downto 0);
        flag : IN STD_LOGIC;
        ap_return : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component pmsm_mul_mul_25s_g8j IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (24 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        dout : OUT STD_LOGIC_VECTOR (40 downto 0) );
    end component;



begin
    grp_calc_sin_cos_fu_96 : component calc_sin_cos
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_calc_sin_cos_fu_96_ap_start,
        ap_done => grp_calc_sin_cos_fu_96_ap_done,
        ap_idle => grp_calc_sin_cos_fu_96_ap_idle,
        ap_ready => grp_calc_sin_cos_fu_96_ap_ready,
        theta_aux_V => theta_V,
        flag => grp_calc_sin_cos_fu_96_flag,
        ap_return => grp_calc_sin_cos_fu_96_ap_return);

    grp_calc_sin_cos_fu_105 : component calc_sin_cos
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_calc_sin_cos_fu_105_ap_start,
        ap_done => grp_calc_sin_cos_fu_105_ap_done,
        ap_idle => grp_calc_sin_cos_fu_105_ap_idle,
        ap_ready => grp_calc_sin_cos_fu_105_ap_ready,
        theta_aux_V => theta_V,
        flag => grp_calc_sin_cos_fu_105_flag,
        ap_return => grp_calc_sin_cos_fu_105_ap_return);

    grp_calc_sin_cos_fu_114 : component calc_sin_cos
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_calc_sin_cos_fu_114_ap_start,
        ap_done => grp_calc_sin_cos_fu_114_ap_done,
        ap_idle => grp_calc_sin_cos_fu_114_ap_idle,
        ap_ready => grp_calc_sin_cos_fu_114_ap_ready,
        theta_aux_V => this_assign_1_reg_1251,
        flag => grp_calc_sin_cos_fu_114_flag,
        ap_return => grp_calc_sin_cos_fu_114_ap_return);

    grp_calc_sin_cos_fu_123 : component calc_sin_cos
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_calc_sin_cos_fu_123_ap_start,
        ap_done => grp_calc_sin_cos_fu_123_ap_done,
        ap_idle => grp_calc_sin_cos_fu_123_ap_idle,
        ap_ready => grp_calc_sin_cos_fu_123_ap_ready,
        theta_aux_V => this_assign_11_1_reg_1256,
        flag => grp_calc_sin_cos_fu_123_flag,
        ap_return => grp_calc_sin_cos_fu_123_ap_return);

    grp_calc_sin_cos_fu_132 : component calc_sin_cos
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_calc_sin_cos_fu_132_ap_start,
        ap_done => grp_calc_sin_cos_fu_132_ap_done,
        ap_idle => grp_calc_sin_cos_fu_132_ap_idle,
        ap_ready => grp_calc_sin_cos_fu_132_ap_ready,
        theta_aux_V => this_assign_12_1_reg_1261,
        flag => grp_calc_sin_cos_fu_132_flag,
        ap_return => grp_calc_sin_cos_fu_132_ap_return);

    grp_calc_sin_cos_fu_141 : component calc_sin_cos
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_calc_sin_cos_fu_141_ap_start,
        ap_done => grp_calc_sin_cos_fu_141_ap_done,
        ap_idle => grp_calc_sin_cos_fu_141_ap_idle,
        ap_ready => grp_calc_sin_cos_fu_141_ap_ready,
        theta_aux_V => this_assign_13_1_reg_1266,
        flag => grp_calc_sin_cos_fu_141_flag,
        ap_return => grp_calc_sin_cos_fu_141_ap_return);

    pmsm_mul_mul_25s_g8j_U29 : component pmsm_mul_mul_25s_g8j
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 25,
        din1_WIDTH => 16,
        dout_WIDTH => 41)
    port map (
        din0 => p_Val2_s_fu_1209_p0,
        din1 => p_s_reg_1271,
        dout => p_Val2_s_fu_1209_p2);

    pmsm_mul_mul_25s_g8j_U30 : component pmsm_mul_mul_25s_g8j
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 25,
        din1_WIDTH => 16,
        dout_WIDTH => 41)
    port map (
        din0 => p_Val2_74_fu_1215_p0,
        din1 => p_1_reg_1276,
        dout => p_Val2_74_fu_1215_p2);

    pmsm_mul_mul_25s_g8j_U31 : component pmsm_mul_mul_25s_g8j
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 25,
        din1_WIDTH => 16,
        dout_WIDTH => 41)
    port map (
        din0 => p_Val2_80_fu_1221_p0,
        din1 => p_2_reg_1281,
        dout => p_Val2_80_fu_1221_p2);

    pmsm_mul_mul_25s_g8j_U32 : component pmsm_mul_mul_25s_g8j
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 25,
        din1_WIDTH => 16,
        dout_WIDTH => 41)
    port map (
        din0 => p_Val2_6_45_fu_1227_p0,
        din1 => p_3_reg_1286,
        dout => p_Val2_6_45_fu_1227_p2);

    pmsm_mul_mul_25s_g8j_U33 : component pmsm_mul_mul_25s_g8j
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 25,
        din1_WIDTH => 16,
        dout_WIDTH => 41)
    port map (
        din0 => p_Val2_86_fu_1233_p0,
        din1 => p_4_reg_1291,
        dout => p_Val2_86_fu_1233_p2);

    pmsm_mul_mul_25s_g8j_U34 : component pmsm_mul_mul_25s_g8j
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 25,
        din1_WIDTH => 16,
        dout_WIDTH => 41)
    port map (
        din0 => p_Val2_7_46_fu_1239_p0,
        din1 => p_0_reg_1296,
        dout => p_Val2_7_46_fu_1239_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_reg_grp_calc_sin_cos_fu_105_ap_start_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_grp_calc_sin_cos_fu_105_ap_start <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    ap_reg_grp_calc_sin_cos_fu_105_ap_start <= ap_const_logic_1;
                elsif ((grp_calc_sin_cos_fu_105_ap_ready = ap_const_logic_1)) then 
                    ap_reg_grp_calc_sin_cos_fu_105_ap_start <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_reg_grp_calc_sin_cos_fu_114_ap_start_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_grp_calc_sin_cos_fu_114_ap_start <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    ap_reg_grp_calc_sin_cos_fu_114_ap_start <= ap_const_logic_1;
                elsif ((grp_calc_sin_cos_fu_114_ap_ready = ap_const_logic_1)) then 
                    ap_reg_grp_calc_sin_cos_fu_114_ap_start <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_reg_grp_calc_sin_cos_fu_123_ap_start_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_grp_calc_sin_cos_fu_123_ap_start <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    ap_reg_grp_calc_sin_cos_fu_123_ap_start <= ap_const_logic_1;
                elsif ((grp_calc_sin_cos_fu_123_ap_ready = ap_const_logic_1)) then 
                    ap_reg_grp_calc_sin_cos_fu_123_ap_start <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_reg_grp_calc_sin_cos_fu_132_ap_start_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_grp_calc_sin_cos_fu_132_ap_start <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    ap_reg_grp_calc_sin_cos_fu_132_ap_start <= ap_const_logic_1;
                elsif ((grp_calc_sin_cos_fu_132_ap_ready = ap_const_logic_1)) then 
                    ap_reg_grp_calc_sin_cos_fu_132_ap_start <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_reg_grp_calc_sin_cos_fu_141_ap_start_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_grp_calc_sin_cos_fu_141_ap_start <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    ap_reg_grp_calc_sin_cos_fu_141_ap_start <= ap_const_logic_1;
                elsif ((grp_calc_sin_cos_fu_141_ap_ready = ap_const_logic_1)) then 
                    ap_reg_grp_calc_sin_cos_fu_141_ap_start <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_reg_grp_calc_sin_cos_fu_96_ap_start_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_grp_calc_sin_cos_fu_96_ap_start <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    ap_reg_grp_calc_sin_cos_fu_96_ap_start <= ap_const_logic_1;
                elsif ((grp_calc_sin_cos_fu_96_ap_ready = ap_const_logic_1)) then 
                    ap_reg_grp_calc_sin_cos_fu_96_ap_start <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                Range1_all_ones_21_reg_1419 <= Range1_all_ones_21_fu_680_p2;
                Range1_all_ones_24_reg_1466 <= Range1_all_ones_24_fu_828_p2;
                Range1_all_ones_reg_1372 <= Range1_all_ones_fu_532_p2;
                Range1_all_zeros_2_reg_1426 <= Range1_all_zeros_2_fu_686_p2;
                Range1_all_zeros_3_reg_1473 <= Range1_all_zeros_3_fu_834_p2;
                Range1_all_zeros_reg_1379 <= Range1_all_zeros_fu_538_p2;
                Range2_all_ones_7_reg_1414 <= Range2_all_ones_7_fu_664_p2;
                Range2_all_ones_8_reg_1461 <= Range2_all_ones_8_fu_812_p2;
                Range2_all_ones_reg_1367 <= Range2_all_ones_fu_516_p2;
                carry_10_reg_1454 <= carry_10_fu_796_p2;
                carry_9_reg_1407 <= carry_9_fu_648_p2;
                carry_reg_1360 <= carry_fu_500_p2;
                newsignbit_19_reg_1401 <= p_Val2_83_fu_628_p2(24 downto 24);
                newsignbit_21_reg_1448 <= p_Val2_89_fu_776_p2(24 downto 24);
                newsignbit_reg_1354 <= p_Val2_77_fu_480_p2(24 downto 24);
                p_Val2_77_reg_1348 <= p_Val2_77_fu_480_p2;
                p_Val2_83_reg_1395 <= p_Val2_83_fu_628_p2;
                p_Val2_89_reg_1442 <= p_Val2_89_fu_776_p2;
                signbit_11_reg_1389 <= p_Val2_81_fu_554_p2(41 downto 41);
                signbit_12_reg_1436 <= p_Val2_87_fu_702_p2(41 downto 41);
                signbit_reg_1342 <= p_Val2_75_fu_406_p2(41 downto 41);
                tmp_15_reg_1384 <= tmp_15_fu_550_p2;
                tmp_24_reg_1431 <= tmp_24_fu_698_p2;
                tmp_reg_1337 <= tmp_fu_402_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state3_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                p_0_reg_1296 <= grp_calc_sin_cos_fu_141_ap_return;
                p_1_reg_1276 <= grp_calc_sin_cos_fu_105_ap_return;
                p_2_reg_1281 <= grp_calc_sin_cos_fu_114_ap_return;
                p_3_reg_1286 <= grp_calc_sin_cos_fu_123_ap_return;
                p_4_reg_1291 <= grp_calc_sin_cos_fu_132_ap_return;
                p_s_reg_1271 <= grp_calc_sin_cos_fu_96_ap_return;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                p_Val2_6_45_reg_1319 <= p_Val2_6_45_fu_1227_p2;
                p_Val2_74_reg_1307 <= p_Val2_74_fu_1215_p2;
                p_Val2_7_46_reg_1331 <= p_Val2_7_46_fu_1239_p2;
                p_Val2_80_reg_1313 <= p_Val2_80_fu_1221_p2;
                p_Val2_86_reg_1325 <= p_Val2_86_fu_1233_p2;
                p_Val2_s_reg_1301 <= p_Val2_s_fu_1209_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                this_assign_11_1_reg_1256 <= this_assign_11_1_fu_254_p3;
                this_assign_12_1_reg_1261 <= this_assign_12_1_fu_342_p3;
                this_assign_13_1_reg_1266 <= this_assign_13_1_fu_362_p3;
                this_assign_1_reg_1251 <= this_assign_1_fu_234_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state3, ap_block_state3_on_subcall_done)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((ap_const_boolean_0 = ap_block_state3_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;
        OP2_V_2_fu_380_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(q_V),41));

        OP2_V_fu_373_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(d_V),41));

    Range1_all_ones_21_fu_680_p2 <= "1" when (tmp_23_fu_670_p4 = ap_const_lv4_F) else "0";
    Range1_all_ones_24_fu_828_p2 <= "1" when (tmp_32_fu_818_p4 = ap_const_lv4_F) else "0";
    Range1_all_ones_fu_532_p2 <= "1" when (tmp_14_fu_522_p4 = ap_const_lv4_F) else "0";
    Range1_all_zeros_2_fu_686_p2 <= "1" when (tmp_23_fu_670_p4 = ap_const_lv4_0) else "0";
    Range1_all_zeros_3_fu_834_p2 <= "1" when (tmp_32_fu_818_p4 = ap_const_lv4_0) else "0";
    Range1_all_zeros_fu_538_p2 <= "1" when (tmp_14_fu_522_p4 = ap_const_lv4_0) else "0";
    Range2_all_ones_7_fu_664_p2 <= "1" when (tmp_22_fu_654_p4 = ap_const_lv3_7) else "0";
    Range2_all_ones_8_fu_812_p2 <= "1" when (tmp_31_fu_802_p4 = ap_const_lv3_7) else "0";
    Range2_all_ones_fu_516_p2 <= "1" when (tmp_13_fu_506_p4 = ap_const_lv3_7) else "0";
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);

    ap_block_state3_on_subcall_done_assign_proc : process(grp_calc_sin_cos_fu_96_ap_done, grp_calc_sin_cos_fu_105_ap_done, grp_calc_sin_cos_fu_114_ap_done, grp_calc_sin_cos_fu_123_ap_done, grp_calc_sin_cos_fu_132_ap_done, grp_calc_sin_cos_fu_141_ap_done)
    begin
                ap_block_state3_on_subcall_done <= ((grp_calc_sin_cos_fu_141_ap_done = ap_const_logic_0) or (grp_calc_sin_cos_fu_132_ap_done = ap_const_logic_0) or (grp_calc_sin_cos_fu_123_ap_done = ap_const_logic_0) or (grp_calc_sin_cos_fu_114_ap_done = ap_const_logic_0) or (grp_calc_sin_cos_fu_105_ap_done = ap_const_logic_0) or (grp_calc_sin_cos_fu_96_ap_done = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_return_0 <= ssdm_int_V_write_ass_fu_949_p3;
    ap_return_1 <= ssdm_int_V_write_ass_1_fu_1066_p3;
    ap_return_2 <= ssdm_int_V_write_ass_2_fu_1183_p3;
    brmerge3_fu_212_p2 <= (tmp_83_fu_182_p2 or newsignbit_18_fu_174_p3);
    brmerge40_demorgan_i_1_fu_1129_p2 <= (newsignbit_21_reg_1448 and deleted_ones_14_fu_1097_p3);
    brmerge40_demorgan_i_2_fu_895_p2 <= (newsignbit_reg_1354 and deleted_ones_fu_863_p3);
    brmerge40_demorgan_i_fu_1012_p2 <= (newsignbit_19_reg_1401 and deleted_ones_11_fu_980_p3);
    brmerge4_fu_248_p2 <= (overflow_14_fu_188_p2 or brmerge_i_i17_not_fu_242_p2);
    brmerge7_fu_320_p2 <= (tmp_91_fu_290_p2 or newsignbit_20_fu_282_p3);
    brmerge8_fu_356_p2 <= (overflow_16_fu_296_p2 or brmerge_i_i20_not_fu_350_p2);
    brmerge_i3_fu_996_p2 <= (p_not_i_fu_990_p2 or newsignbit_19_reg_1401);
    brmerge_i4_fu_1113_p2 <= (p_not_i4_fu_1107_p2 or newsignbit_21_reg_1448);
    brmerge_i_fu_879_p2 <= (p_not_i3_fu_873_p2 or newsignbit_reg_1354);
    brmerge_i_i16_fu_206_p2 <= (newsignbit_18_fu_174_p3 xor isneg_fu_160_p3);
    brmerge_i_i17_fu_1034_p2 <= (underflow_19_fu_1029_p2 or overflow_15_fu_1006_p2);
    brmerge_i_i17_not_fu_242_p2 <= (brmerge_i_i16_fu_206_p2 xor ap_const_lv1_1);
    brmerge_i_i18_fu_314_p2 <= (newsignbit_20_fu_282_p3 xor isneg_6_fu_268_p3);
    brmerge_i_i19_fu_1151_p2 <= (underflow_21_fu_1146_p2 or overflow_17_fu_1123_p2);
    brmerge_i_i20_not_fu_350_p2 <= (brmerge_i_i18_fu_314_p2 xor ap_const_lv1_1);
    brmerge_i_i_fu_917_p2 <= (underflow_fu_912_p2 or overflow_fu_889_p2);
    carry_10_fu_796_p2 <= (tmp_96_fu_790_p2 and tmp_166_fu_744_p3);
    carry_9_fu_648_p2 <= (tmp_88_fu_642_p2 and tmp_157_fu_596_p3);
    carry_fu_500_p2 <= (tmp_79_fu_494_p2 and tmp_148_fu_448_p3);
    deleted_ones_11_fu_980_p3 <= 
        p_41_i_fu_975_p2 when (carry_9_reg_1407(0) = '1') else 
        Range1_all_ones_21_reg_1419;
    deleted_ones_14_fu_1097_p3 <= 
        p_41_i1_fu_1092_p2 when (carry_10_reg_1454(0) = '1') else 
        Range1_all_ones_24_reg_1466;
    deleted_ones_fu_863_p3 <= 
        p_41_i9_fu_858_p2 when (carry_reg_1360(0) = '1') else 
        Range1_all_ones_reg_1372;
    deleted_zeros_10_fu_1081_p3 <= 
        Range1_all_ones_24_reg_1466 when (carry_10_reg_1454(0) = '1') else 
        Range1_all_zeros_3_reg_1473;
    deleted_zeros_9_fu_964_p3 <= 
        Range1_all_ones_21_reg_1419 when (carry_9_reg_1407(0) = '1') else 
        Range1_all_zeros_2_reg_1426;
    deleted_zeros_fu_847_p3 <= 
        Range1_all_ones_reg_1372 when (carry_reg_1360(0) = '1') else 
        Range1_all_zeros_reg_1379;
    grp_calc_sin_cos_fu_105_ap_start <= ap_reg_grp_calc_sin_cos_fu_105_ap_start;
    grp_calc_sin_cos_fu_105_flag <= ap_const_logic_0;
    grp_calc_sin_cos_fu_114_ap_start <= ap_reg_grp_calc_sin_cos_fu_114_ap_start;
    grp_calc_sin_cos_fu_114_flag <= ap_const_logic_1;
    grp_calc_sin_cos_fu_123_ap_start <= ap_reg_grp_calc_sin_cos_fu_123_ap_start;
    grp_calc_sin_cos_fu_123_flag <= ap_const_logic_0;
    grp_calc_sin_cos_fu_132_ap_start <= ap_reg_grp_calc_sin_cos_fu_132_ap_start;
    grp_calc_sin_cos_fu_132_flag <= ap_const_logic_1;
    grp_calc_sin_cos_fu_141_ap_start <= ap_reg_grp_calc_sin_cos_fu_141_ap_start;
    grp_calc_sin_cos_fu_141_flag <= ap_const_logic_0;
    grp_calc_sin_cos_fu_96_ap_start <= ap_reg_grp_calc_sin_cos_fu_96_ap_start;
    grp_calc_sin_cos_fu_96_flag <= ap_const_logic_1;
    isneg_6_fu_268_p3 <= p_Val2_84_fu_262_p2(16 downto 16);
    isneg_fu_160_p3 <= p_Val2_78_fu_154_p2(16 downto 16);
    newsignbit_18_fu_174_p3 <= p_Val2_79_fu_168_p2(15 downto 15);
    newsignbit_19_fu_634_p3 <= p_Val2_83_fu_628_p2(24 downto 24);
    newsignbit_20_fu_282_p3 <= p_Val2_85_fu_276_p2(15 downto 15);
    newsignbit_21_fu_782_p3 <= p_Val2_89_fu_776_p2(24 downto 24);
    newsignbit_fu_486_p3 <= p_Val2_77_fu_480_p2(24 downto 24);
    overflow_14_fu_188_p2 <= (tmp_83_fu_182_p2 and newsignbit_18_fu_174_p3);
    overflow_15_fu_1006_p2 <= (tmp_90_fu_1001_p2 and brmerge_i3_fu_996_p2);
    overflow_16_fu_296_p2 <= (tmp_91_fu_290_p2 and newsignbit_20_fu_282_p3);
    overflow_17_fu_1123_p2 <= (tmp_98_fu_1118_p2 and brmerge_i4_fu_1113_p2);
    overflow_fu_889_p2 <= (tmp_81_fu_884_p2 and brmerge_i_fu_879_p2);
    p_38_i1_fu_1103_p2 <= (carry_10_reg_1454 and Range1_all_ones_24_reg_1466);
    p_38_i9_fu_869_p2 <= (carry_reg_1360 and Range1_all_ones_reg_1372);
    p_38_i_fu_986_p2 <= (carry_9_reg_1407 and Range1_all_ones_21_reg_1419);
    p_41_i1_fu_1092_p2 <= (tmp_97_fu_1086_p2 and Range2_all_ones_8_reg_1461);
    p_41_i9_fu_858_p2 <= (tmp_80_fu_852_p2 and Range2_all_ones_reg_1367);
    p_41_i_fu_975_p2 <= (tmp_89_fu_969_p2 and Range2_all_ones_7_reg_1414);
    p_Val2_103_mux_fu_1052_p3 <= 
        ap_const_lv25_FFFFFF when (brmerge_i_i17_fu_1034_p2(0) = '1') else 
        p_Val2_83_reg_1395;
    p_Val2_105_mux_fu_326_p3 <= 
        ap_const_lv16_7FFF when (brmerge_i_i18_fu_314_p2(0) = '1') else 
        p_Val2_85_fu_276_p2;
    p_Val2_110_mux_fu_1169_p3 <= 
        ap_const_lv25_FFFFFF when (brmerge_i_i19_fu_1151_p2(0) = '1') else 
        p_Val2_89_reg_1442;
    p_Val2_6_45_fu_1227_p0 <= OP2_V_2_fu_380_p1(25 - 1 downto 0);
    p_Val2_6_fu_226_p3 <= 
        ap_const_lv16_8000 when (underflow_18_fu_200_p2(0) = '1') else 
        p_Val2_79_fu_168_p2;
    p_Val2_74_fu_1215_p0 <= OP2_V_2_fu_380_p1(25 - 1 downto 0);
    p_Val2_75_fu_406_p2 <= std_logic_vector(signed(tmp_77_fu_399_p1) + signed(tmp_s_fu_396_p1));
    p_Val2_76_fu_420_p4 <= tmp_fu_402_p2(37 downto 13);
    p_Val2_77_fu_480_p2 <= std_logic_vector(unsigned(p_Val2_76_fu_420_p4) + unsigned(tmp_78_fu_476_p1));
    p_Val2_78_fu_154_p2 <= std_logic_vector(signed(ap_const_lv17_1FBD0) + signed(tmp_82_fu_150_p1));
    p_Val2_79_fu_168_p2 <= std_logic_vector(signed(ap_const_lv16_FBD0) + signed(theta_V));
    p_Val2_7_46_fu_1239_p0 <= OP2_V_2_fu_380_p1(25 - 1 downto 0);
    p_Val2_7_fu_1059_p3 <= 
        ap_const_lv25_1000000 when (underflow_19_fu_1029_p2(0) = '1') else 
        p_Val2_83_reg_1395;
    p_Val2_80_fu_1221_p0 <= OP2_V_fu_373_p1(25 - 1 downto 0);
    p_Val2_81_fu_554_p2 <= std_logic_vector(signed(tmp_86_fu_547_p1) + signed(tmp_85_fu_544_p1));
    p_Val2_82_fu_568_p4 <= tmp_15_fu_550_p2(37 downto 13);
    p_Val2_83_fu_628_p2 <= std_logic_vector(unsigned(p_Val2_82_fu_568_p4) + unsigned(tmp_87_fu_624_p1));
    p_Val2_84_fu_262_p2 <= std_logic_vector(unsigned(ap_const_lv17_430) + unsigned(tmp_82_fu_150_p1));
    p_Val2_85_fu_276_p2 <= std_logic_vector(unsigned(ap_const_lv16_430) + unsigned(theta_V));
    p_Val2_86_fu_1233_p0 <= OP2_V_fu_373_p1(25 - 1 downto 0);
    p_Val2_87_fu_702_p2 <= std_logic_vector(signed(tmp_94_fu_695_p1) + signed(tmp_93_fu_692_p1));
    p_Val2_88_fu_716_p4 <= tmp_24_fu_698_p2(37 downto 13);
    p_Val2_89_fu_776_p2 <= std_logic_vector(unsigned(p_Val2_88_fu_716_p4) + unsigned(tmp_95_fu_772_p1));
    p_Val2_8_fu_334_p3 <= 
        ap_const_lv16_8000 when (underflow_20_fu_308_p2(0) = '1') else 
        p_Val2_85_fu_276_p2;
    p_Val2_95_mux_fu_935_p3 <= 
        ap_const_lv25_FFFFFF when (brmerge_i_i_fu_917_p2(0) = '1') else 
        p_Val2_77_reg_1348;
    p_Val2_98_mux_fu_218_p3 <= 
        ap_const_lv16_7FFF when (brmerge_i_i16_fu_206_p2(0) = '1') else 
        p_Val2_79_fu_168_p2;
    p_Val2_9_fu_1176_p3 <= 
        ap_const_lv25_1000000 when (underflow_21_fu_1146_p2(0) = '1') else 
        p_Val2_89_reg_1442;
    p_Val2_s_44_fu_942_p3 <= 
        ap_const_lv25_1000000 when (underflow_fu_912_p2(0) = '1') else 
        p_Val2_77_reg_1348;
    p_Val2_s_fu_1209_p0 <= OP2_V_fu_373_p1(25 - 1 downto 0);
    p_not_i3_fu_873_p2 <= (deleted_zeros_fu_847_p3 xor ap_const_lv1_1);
    p_not_i4_fu_1107_p2 <= (deleted_zeros_10_fu_1081_p3 xor ap_const_lv1_1);
    p_not_i_fu_990_p2 <= (deleted_zeros_9_fu_964_p3 xor ap_const_lv1_1);
    qb_assign_3_fu_618_p2 <= (r_i_i5_fu_612_p2 and qbit_12_fu_578_p3);
    qb_assign_4_fu_766_p2 <= (r_i_i6_fu_760_p2 and qbit_13_fu_726_p3);
    qb_assign_s_fu_470_p2 <= (r_i_i_fu_464_p2 and qbit_fu_430_p3);
    qbit_12_fu_578_p3 <= tmp_15_fu_550_p2(12 downto 12);
    qbit_13_fu_726_p3 <= tmp_24_fu_698_p2(12 downto 12);
    qbit_fu_430_p3 <= tmp_fu_402_p2(12 downto 12);
    r_12_fu_590_p2 <= "0" when (tmp_156_fu_586_p1 = ap_const_lv12_0) else "1";
    r_13_fu_738_p2 <= "0" when (tmp_165_fu_734_p1 = ap_const_lv12_0) else "1";
    r_fu_442_p2 <= "0" when (tmp_147_fu_438_p1 = ap_const_lv12_0) else "1";
    r_i_i5_fu_612_p2 <= (tmp_158_fu_604_p3 or r_12_fu_590_p2);
    r_i_i6_fu_760_p2 <= (tmp_167_fu_752_p3 or r_13_fu_738_p2);
    r_i_i_fu_464_p2 <= (tmp_149_fu_456_p3 or r_fu_442_p2);
    ssdm_int_V_write_ass_1_fu_1066_p3 <= 
        p_Val2_103_mux_fu_1052_p3 when (underflow_17_not_fu_1046_p2(0) = '1') else 
        p_Val2_7_fu_1059_p3;
    ssdm_int_V_write_ass_2_fu_1183_p3 <= 
        p_Val2_110_mux_fu_1169_p3 when (underflow_19_not_fu_1163_p2(0) = '1') else 
        p_Val2_9_fu_1176_p3;
    ssdm_int_V_write_ass_fu_949_p3 <= 
        p_Val2_95_mux_fu_935_p3 when (underflow_not_fu_929_p2(0) = '1') else 
        p_Val2_s_44_fu_942_p3;
    this_assign_11_1_fu_254_p3 <= 
        p_Val2_98_mux_fu_218_p3 when (brmerge4_fu_248_p2(0) = '1') else 
        p_Val2_6_fu_226_p3;
    this_assign_12_1_fu_342_p3 <= 
        p_Val2_105_mux_fu_326_p3 when (brmerge7_fu_320_p2(0) = '1') else 
        p_Val2_8_fu_334_p3;
    this_assign_13_1_fu_362_p3 <= 
        p_Val2_105_mux_fu_326_p3 when (brmerge8_fu_356_p2(0) = '1') else 
        p_Val2_8_fu_334_p3;
    this_assign_1_fu_234_p3 <= 
        p_Val2_98_mux_fu_218_p3 when (brmerge3_fu_212_p2(0) = '1') else 
        p_Val2_6_fu_226_p3;
    tmp1_demorgan_fu_900_p2 <= (p_38_i9_fu_869_p2 or brmerge40_demorgan_i_2_fu_895_p2);
    tmp1_fu_906_p2 <= (tmp1_demorgan_fu_900_p2 xor ap_const_lv1_1);
    tmp2_fu_923_p2 <= (tmp_81_fu_884_p2 or brmerge40_demorgan_i_2_fu_895_p2);
    tmp3_demorgan_fu_1017_p2 <= (p_38_i_fu_986_p2 or brmerge40_demorgan_i_fu_1012_p2);
    tmp3_fu_1023_p2 <= (tmp3_demorgan_fu_1017_p2 xor ap_const_lv1_1);
    tmp4_fu_1040_p2 <= (tmp_90_fu_1001_p2 or brmerge40_demorgan_i_fu_1012_p2);
    tmp5_demorgan_fu_1134_p2 <= (p_38_i1_fu_1103_p2 or brmerge40_demorgan_i_1_fu_1129_p2);
    tmp5_fu_1140_p2 <= (tmp5_demorgan_fu_1134_p2 xor ap_const_lv1_1);
    tmp6_fu_1157_p2 <= (tmp_98_fu_1118_p2 or brmerge40_demorgan_i_1_fu_1129_p2);
    tmp_13_fu_506_p4 <= p_Val2_75_fu_406_p2(41 downto 39);
    tmp_147_fu_438_p1 <= tmp_fu_402_p2(12 - 1 downto 0);
    tmp_148_fu_448_p3 <= tmp_fu_402_p2(37 downto 37);
    tmp_149_fu_456_p3 <= tmp_fu_402_p2(13 downto 13);
    tmp_14_fu_522_p4 <= p_Val2_75_fu_406_p2(41 downto 38);
    tmp_151_fu_840_p3 <= tmp_reg_1337(38 downto 38);
    tmp_156_fu_586_p1 <= tmp_15_fu_550_p2(12 - 1 downto 0);
    tmp_157_fu_596_p3 <= tmp_15_fu_550_p2(37 downto 37);
    tmp_158_fu_604_p3 <= tmp_15_fu_550_p2(13 downto 13);
    tmp_15_fu_550_p2 <= std_logic_vector(signed(p_Val2_80_reg_1313) + signed(p_Val2_6_45_reg_1319));
    tmp_160_fu_957_p3 <= tmp_15_reg_1384(38 downto 38);
    tmp_165_fu_734_p1 <= tmp_24_fu_698_p2(12 - 1 downto 0);
    tmp_166_fu_744_p3 <= tmp_24_fu_698_p2(37 downto 37);
    tmp_167_fu_752_p3 <= tmp_24_fu_698_p2(13 downto 13);
    tmp_169_fu_1074_p3 <= tmp_24_reg_1431(38 downto 38);
    tmp_22_fu_654_p4 <= p_Val2_81_fu_554_p2(41 downto 39);
    tmp_23_fu_670_p4 <= p_Val2_81_fu_554_p2(41 downto 38);
    tmp_24_fu_698_p2 <= std_logic_vector(signed(p_Val2_86_reg_1325) + signed(p_Val2_7_46_reg_1331));
    tmp_31_fu_802_p4 <= p_Val2_87_fu_702_p2(41 downto 39);
    tmp_32_fu_818_p4 <= p_Val2_87_fu_702_p2(41 downto 38);
        tmp_77_fu_399_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Val2_74_reg_1307),42));

    tmp_78_fu_476_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(qb_assign_s_fu_470_p2),25));
    tmp_79_fu_494_p2 <= (newsignbit_fu_486_p3 xor ap_const_lv1_1);
    tmp_80_fu_852_p2 <= (tmp_151_fu_840_p3 xor ap_const_lv1_1);
    tmp_81_fu_884_p2 <= (signbit_reg_1342 xor ap_const_lv1_1);
        tmp_82_fu_150_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(theta_V),17));

    tmp_83_fu_182_p2 <= (isneg_fu_160_p3 xor ap_const_lv1_1);
    tmp_84_fu_194_p2 <= (newsignbit_18_fu_174_p3 xor ap_const_lv1_1);
        tmp_85_fu_544_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Val2_80_reg_1313),42));

        tmp_86_fu_547_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Val2_6_45_reg_1319),42));

    tmp_87_fu_624_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(qb_assign_3_fu_618_p2),25));
    tmp_88_fu_642_p2 <= (newsignbit_19_fu_634_p3 xor ap_const_lv1_1);
    tmp_89_fu_969_p2 <= (tmp_160_fu_957_p3 xor ap_const_lv1_1);
    tmp_90_fu_1001_p2 <= (signbit_11_reg_1389 xor ap_const_lv1_1);
    tmp_91_fu_290_p2 <= (isneg_6_fu_268_p3 xor ap_const_lv1_1);
    tmp_92_fu_302_p2 <= (newsignbit_20_fu_282_p3 xor ap_const_lv1_1);
        tmp_93_fu_692_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Val2_86_reg_1325),42));

        tmp_94_fu_695_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Val2_7_46_reg_1331),42));

    tmp_95_fu_772_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(qb_assign_4_fu_766_p2),25));
    tmp_96_fu_790_p2 <= (newsignbit_21_fu_782_p3 xor ap_const_lv1_1);
    tmp_97_fu_1086_p2 <= (tmp_169_fu_1074_p3 xor ap_const_lv1_1);
    tmp_98_fu_1118_p2 <= (signbit_12_reg_1436 xor ap_const_lv1_1);
    tmp_fu_402_p2 <= std_logic_vector(signed(p_Val2_s_reg_1301) + signed(p_Val2_74_reg_1307));
        tmp_s_fu_396_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Val2_s_reg_1301),42));

    underflow_17_not_fu_1046_p2 <= (tmp4_fu_1040_p2 or p_38_i_fu_986_p2);
    underflow_18_fu_200_p2 <= (tmp_84_fu_194_p2 and isneg_fu_160_p3);
    underflow_19_fu_1029_p2 <= (tmp3_fu_1023_p2 and signbit_11_reg_1389);
    underflow_19_not_fu_1163_p2 <= (tmp6_fu_1157_p2 or p_38_i1_fu_1103_p2);
    underflow_20_fu_308_p2 <= (tmp_92_fu_302_p2 and isneg_6_fu_268_p3);
    underflow_21_fu_1146_p2 <= (tmp5_fu_1140_p2 and signbit_12_reg_1436);
    underflow_fu_912_p2 <= (tmp1_fu_906_p2 and signbit_reg_1342);
    underflow_not_fu_929_p2 <= (tmp2_fu_923_p2 or p_38_i9_fu_869_p2);
end behav;
