-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2017.4
-- Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity pmsm_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    Is_a_V : IN STD_LOGIC_VECTOR (24 downto 0);
    Is_b_V : IN STD_LOGIC_VECTOR (24 downto 0);
    Is_c_V : IN STD_LOGIC_VECTOR (24 downto 0);
    Wn_o_V : IN STD_LOGIC_VECTOR (24 downto 0);
    Tem_aux_V : OUT STD_LOGIC_VECTOR (26 downto 0);
    Tem_aux_V_ap_vld : OUT STD_LOGIC;
    Fem_a_V : OUT STD_LOGIC_VECTOR (24 downto 0);
    Fem_a_V_ap_vld : OUT STD_LOGIC;
    Fem_b_V : OUT STD_LOGIC_VECTOR (24 downto 0);
    Fem_b_V_ap_vld : OUT STD_LOGIC;
    Fem_c_V : OUT STD_LOGIC_VECTOR (24 downto 0);
    Fem_c_V_ap_vld : OUT STD_LOGIC );
end;


architecture behav of pmsm_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (19 downto 0) := "00000000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (19 downto 0) := "00000000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (19 downto 0) := "00000000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (19 downto 0) := "00000001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (19 downto 0) := "00000010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (19 downto 0) := "00000100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (19 downto 0) := "00001000000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (19 downto 0) := "00010000000000000000";
    constant ap_ST_fsm_state18 : STD_LOGIC_VECTOR (19 downto 0) := "00100000000000000000";
    constant ap_ST_fsm_state19 : STD_LOGIC_VECTOR (19 downto 0) := "01000000000000000000";
    constant ap_ST_fsm_state20 : STD_LOGIC_VECTOR (19 downto 0) := "10000000000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv9_1FF : STD_LOGIC_VECTOR (8 downto 0) := "111111111";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv40_7FFFFFFFFF : STD_LOGIC_VECTOR (39 downto 0) := "0111111111111111111111111111111111111111";
    constant ap_const_lv40_8000000000 : STD_LOGIC_VECTOR (39 downto 0) := "1000000000000000000000000000000000000000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv22_0 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000000000000";
    constant ap_const_lv32_3E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111110";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv32_3D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111101";
    constant ap_const_lv21_0 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000000000000";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv18_0 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    constant ap_const_lv32_22 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100010";
    constant ap_const_lv32_23 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100011";
    constant ap_const_lv32_24 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100100";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv5_1F : STD_LOGIC_VECTOR (4 downto 0) := "11111";
    constant ap_const_lv16_7FFF : STD_LOGIC_VECTOR (15 downto 0) := "0111111111111111";
    constant ap_const_lv16_8000 : STD_LOGIC_VECTOR (15 downto 0) := "1000000000000000";
    constant ap_const_lv24_0 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv21_FFFFF : STD_LOGIC_VECTOR (20 downto 0) := "011111111111111111111";
    constant ap_const_lv21_100000 : STD_LOGIC_VECTOR (20 downto 0) := "100000000000000000000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_39 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111001";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv30_0 : STD_LOGIC_VECTOR (29 downto 0) := "000000000000000000000000000000";
    constant ap_const_lv32_1A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011010";
    constant ap_const_lv32_3B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111011";
    constant ap_const_lv32_3A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111010";
    constant ap_const_lv67_6 : STD_LOGIC_VECTOR (66 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000110";
    constant ap_const_lv27_3FFFFFF : STD_LOGIC_VECTOR (26 downto 0) := "011111111111111111111111111";
    constant ap_const_lv27_4000000 : STD_LOGIC_VECTOR (26 downto 0) := "100000000000000000000000000";
    constant ap_const_lv17_0 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    constant ap_const_lv32_42 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000010";
    constant ap_const_lv59_F4240 : STD_LOGIC_VECTOR (58 downto 0) := "00000000000000000000000000000000000000011110100001001000000";
    constant ap_const_lv32_34 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110100";
    constant ap_const_lv32_35 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110101";
    constant ap_const_lv32_2B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101011";
    constant ap_const_lv32_2A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101010";
    constant ap_const_lv42_0 : STD_LOGIC_VECTOR (41 downto 0) := "000000000000000000000000000000000000000000";
    constant ap_const_lv32_43 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000011";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv6_3F : STD_LOGIC_VECTOR (5 downto 0) := "111111";
    constant ap_const_lv52_7FFFFFFFFFFFF : STD_LOGIC_VECTOR (51 downto 0) := "0111111111111111111111111111111111111111111111111111";
    constant ap_const_lv52_8000000000000 : STD_LOGIC_VECTOR (51 downto 0) := "1000000000000000000000000000000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv25_FFFFFF : STD_LOGIC_VECTOR (24 downto 0) := "0111111111111111111111111";
    constant ap_const_lv25_1000000 : STD_LOGIC_VECTOR (24 downto 0) := "1000000000000000000000000";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv32_38 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111000";
    constant ap_const_lv26_0 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000000000000";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal in_ant_V_2 : STD_LOGIC_VECTOR (39 downto 0) := "0000000000000000000000000000000000000000";
    signal out_ant_V : STD_LOGIC_VECTOR (39 downto 0) := "0000000000000000000000000000000000000000";
    signal Is_d_V : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000000000";
    signal Is_q_V : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000000000";
    signal in_ant_V : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000000000000000000000";
    signal in_ant_V_3 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000000000000000000000";
    signal tmp_fu_348_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_reg_2915 : STD_LOGIC_VECTOR (23 downto 0);
    signal overflow_fu_388_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal overflow_reg_2920 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_fu_412_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_reg_2926 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_10_fu_454_p3 : STD_LOGIC_VECTOR (39 downto 0);
    signal p_Val2_10_reg_2933 : STD_LOGIC_VECTOR (39 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal p_Val2_11_reg_2941 : STD_LOGIC_VECTOR (39 downto 0);
    signal r_V_fu_474_p2 : STD_LOGIC_VECTOR (40 downto 0);
    signal r_V_reg_2946 : STD_LOGIC_VECTOR (40 downto 0);
    signal signbit_reg_2951 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal tmp_43_reg_2960 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_16_fu_599_p2 : STD_LOGIC_VECTOR (39 downto 0);
    signal p_Val2_16_reg_2966 : STD_LOGIC_VECTOR (39 downto 0);
    signal newsignbit_1_reg_2972 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_128_i_fu_638_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_128_i_reg_2981 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal p_38_i_i_fu_643_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_38_i_i_reg_2986 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_1_fu_675_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_1_reg_2991 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_89_mux_i_fu_686_p3 : STD_LOGIC_VECTOR (39 downto 0);
    signal p_Val2_89_mux_i_reg_2996 : STD_LOGIC_VECTOR (39 downto 0);
    signal signbit_1_reg_3001 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal p_Val2_4_fu_789_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Val2_4_reg_3007 : STD_LOGIC_VECTOR (15 downto 0);
    signal newsignbit_2_fu_795_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal newsignbit_2_reg_3013 : STD_LOGIC_VECTOR (0 downto 0);
    signal carry_fu_809_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal carry_reg_3018 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_ones_fu_849_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_ones_reg_3024 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_zeros_fu_855_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_zeros_reg_3030 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge40_demorgan_i_fu_881_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge40_demorgan_i_reg_3035 : STD_LOGIC_VECTOR (0 downto 0);
    signal this_assign_s_fu_965_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal this_assign_s_reg_3041 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal r_V_1_fu_1035_p2 : STD_LOGIC_VECTOR (55 downto 0);
    signal r_V_1_reg_3062 : STD_LOGIC_VECTOR (55 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal r_V_2_fu_1048_p2 : STD_LOGIC_VECTOR (64 downto 0);
    signal r_V_2_reg_3068 : STD_LOGIC_VECTOR (64 downto 0);
    signal r_V_3_fu_1058_p2 : STD_LOGIC_VECTOR (64 downto 0);
    signal r_V_3_reg_3073 : STD_LOGIC_VECTOR (64 downto 0);
    signal tmp_29_fu_1176_p3 : STD_LOGIC_VECTOR (20 downto 0);
    signal tmp_29_reg_3078 : STD_LOGIC_VECTOR (20 downto 0);
    signal tmp_40_fu_1296_p3 : STD_LOGIC_VECTOR (20 downto 0);
    signal tmp_40_reg_3083 : STD_LOGIC_VECTOR (20 downto 0);
    signal p_Val2_6_fu_1326_p2 : STD_LOGIC_VECTOR (62 downto 0);
    signal p_Val2_6_reg_3088 : STD_LOGIC_VECTOR (62 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal signbit_2_reg_3094 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_8_32_fu_1392_p2 : STD_LOGIC_VECTOR (26 downto 0);
    signal p_Val2_8_32_reg_3100 : STD_LOGIC_VECTOR (26 downto 0);
    signal newsignbit_3_reg_3106 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range2_all_ones_1_fu_1416_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range2_all_ones_1_reg_3113 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_ones_1_fu_1432_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_ones_1_reg_3118 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_zeros_1_fu_1438_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_zeros_1_reg_3125 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_4_fu_1625_p2 : STD_LOGIC_VECTOR (38 downto 0);
    signal r_V_4_reg_3140 : STD_LOGIC_VECTOR (38 downto 0);
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal r_V_5_fu_1656_p2 : STD_LOGIC_VECTOR (38 downto 0);
    signal r_V_5_reg_3145 : STD_LOGIC_VECTOR (38 downto 0);
    signal grp_fu_1447_p2 : STD_LOGIC_VECTOR (66 downto 0);
    signal p_Val2_9_reg_3150 : STD_LOGIC_VECTOR (66 downto 0);
    signal ap_CS_fsm_state14 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state14 : signal is "none";
    signal signbit_3_reg_3157 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_74_fu_1676_p1 : STD_LOGIC_VECTOR (41 downto 0);
    signal tmp_74_reg_3166 : STD_LOGIC_VECTOR (41 downto 0);
    signal grp_fu_1456_p2 : STD_LOGIC_VECTOR (66 downto 0);
    signal p_Val2_2_34_reg_3171 : STD_LOGIC_VECTOR (66 downto 0);
    signal p_Val2_20_fu_1702_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal p_Val2_20_reg_3176 : STD_LOGIC_VECTOR (47 downto 0);
    signal signbit_5_reg_3181 : STD_LOGIC_VECTOR (0 downto 0);
    signal newsignbit_7_reg_3187 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_i_reg_3193 : STD_LOGIC_VECTOR (50 downto 0);
    signal tmp_24_reg_3198 : STD_LOGIC_VECTOR (5 downto 0);
    signal signbit_6_reg_3204 : STD_LOGIC_VECTOR (0 downto 0);
    signal newsignbit_9_reg_3210 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_i1_reg_3216 : STD_LOGIC_VECTOR (50 downto 0);
    signal tmp_26_reg_3221 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_Val2_19_fu_1846_p2 : STD_LOGIC_VECTOR (24 downto 0);
    signal p_Val2_19_reg_3227 : STD_LOGIC_VECTOR (24 downto 0);
    signal ap_CS_fsm_state15 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state15 : signal is "none";
    signal newsignbit_4_reg_3233 : STD_LOGIC_VECTOR (0 downto 0);
    signal signbit_4_reg_3241 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_23_fu_1940_p2 : STD_LOGIC_VECTOR (24 downto 0);
    signal p_Val2_23_reg_3250 : STD_LOGIC_VECTOR (24 downto 0);
    signal newsignbit_5_reg_3256 : STD_LOGIC_VECTOR (0 downto 0);
    signal Is_d_dif_V_load_fu_2031_p3 : STD_LOGIC_VECTOR (51 downto 0);
    signal Is_d_dif_V_load_reg_3264 : STD_LOGIC_VECTOR (51 downto 0);
    signal agg_result_V_i_fu_2116_p3 : STD_LOGIC_VECTOR (51 downto 0);
    signal agg_result_V_i_reg_3270 : STD_LOGIC_VECTOR (51 downto 0);
    signal carry_3_fu_2216_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal carry_3_reg_3276 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state16 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state16 : signal is "none";
    signal p_Result_23_not_fu_2221_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_23_not_reg_3281 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge40_demorgan_i_4_fu_2258_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge40_demorgan_i_4_reg_3286 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_5_fu_2275_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_5_reg_3291 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_30_fu_2304_p2 : STD_LOGIC_VECTOR (54 downto 0);
    signal p_Val2_30_reg_3296 : STD_LOGIC_VECTOR (54 downto 0);
    signal tmp_28_fu_2332_p3 : STD_LOGIC_VECTOR (56 downto 0);
    signal tmp_28_reg_3301 : STD_LOGIC_VECTOR (56 downto 0);
    signal p_Val2_34_fu_2358_p2 : STD_LOGIC_VECTOR (54 downto 0);
    signal p_Val2_34_reg_3306 : STD_LOGIC_VECTOR (54 downto 0);
    signal tmp_50_fu_2364_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal tmp_50_reg_3312 : STD_LOGIC_VECTOR (24 downto 0);
    signal r_6_fu_2375_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_6_reg_3317 : STD_LOGIC_VECTOR (0 downto 0);
    signal signbit_7_reg_3322 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state17 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state17 : signal is "none";
    signal tmp_95_reg_3331 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_33_fu_2470_p2 : STD_LOGIC_VECTOR (24 downto 0);
    signal p_Val2_33_reg_3337 : STD_LOGIC_VECTOR (24 downto 0);
    signal newsignbit_10_reg_3343 : STD_LOGIC_VECTOR (0 downto 0);
    signal signbit_8_fu_2518_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal signbit_8_reg_3352 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_101_fu_2543_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_101_reg_3360 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_37_fu_2574_p2 : STD_LOGIC_VECTOR (24 downto 0);
    signal p_Val2_37_reg_3365 : STD_LOGIC_VECTOR (24 downto 0);
    signal newsignbit_11_fu_2580_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal newsignbit_11_reg_3371 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_38_i5_fu_2600_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_38_i5_reg_3379 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_s_fu_2704_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal p_s_reg_3385 : STD_LOGIC_VECTOR (24 downto 0);
    signal ap_CS_fsm_state18 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state18 : signal is "none";
    signal this_assign_6_1_fu_2877_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal this_assign_6_1_reg_3390 : STD_LOGIC_VECTOR (24 downto 0);
    signal grp_dqo_2_abc_fu_284_ap_start : STD_LOGIC;
    signal grp_dqo_2_abc_fu_284_ap_done : STD_LOGIC;
    signal grp_dqo_2_abc_fu_284_ap_idle : STD_LOGIC;
    signal grp_dqo_2_abc_fu_284_ap_ready : STD_LOGIC;
    signal grp_dqo_2_abc_fu_284_ap_return_0 : STD_LOGIC_VECTOR (24 downto 0);
    signal grp_dqo_2_abc_fu_284_ap_return_1 : STD_LOGIC_VECTOR (24 downto 0);
    signal grp_dqo_2_abc_fu_284_ap_return_2 : STD_LOGIC_VECTOR (24 downto 0);
    signal grp_abc_2_dqo_fu_293_ap_start : STD_LOGIC;
    signal grp_abc_2_dqo_fu_293_ap_done : STD_LOGIC;
    signal grp_abc_2_dqo_fu_293_ap_idle : STD_LOGIC;
    signal grp_abc_2_dqo_fu_293_ap_ready : STD_LOGIC;
    signal grp_abc_2_dqo_fu_293_Is_d_V : STD_LOGIC_VECTOR (24 downto 0);
    signal grp_abc_2_dqo_fu_293_Is_d_V_ap_vld : STD_LOGIC;
    signal grp_abc_2_dqo_fu_293_Is_q_V : STD_LOGIC_VECTOR (24 downto 0);
    signal grp_abc_2_dqo_fu_293_Is_q_V_ap_vld : STD_LOGIC;
    signal ap_reg_grp_dqo_2_abc_fu_284_ap_start : STD_LOGIC := '0';
    signal ap_CS_fsm_state19 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state19 : signal is "none";
    signal ap_CS_fsm_state20 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state20 : signal is "none";
    signal ap_reg_grp_abc_2_dqo_fu_293_ap_start : STD_LOGIC := '0';
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal p_Val2_17_fu_708_p3 : STD_LOGIC_VECTOR (39 downto 0);
    signal tmp_167_i_fu_1606_p3 : STD_LOGIC_VECTOR (37 downto 0);
    signal tmp_162_i_fu_1637_p3 : STD_LOGIC_VECTOR (37 downto 0);
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal p_shl_fu_310_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_shl1_fu_322_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal p_shl1_cast_fu_330_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal p_shl_cast_fu_318_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal p_Val2_s_fu_334_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal tmp_6_fu_360_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal newsignbit_fu_352_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_not_i_fu_370_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal isneg_fu_340_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge_i1_fu_376_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_fu_382_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_not38_i_fu_400_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal newsignbit_0_not_i_fu_394_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge39_i_fu_406_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_not_fu_429_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge_i_i1_fu_425_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_1_fu_418_p3 : STD_LOGIC_VECTOR (39 downto 0);
    signal brmerge_fu_434_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_2_mux_fu_439_p3 : STD_LOGIC_VECTOR (39 downto 0);
    signal p_Val2_2_fu_447_p3 : STD_LOGIC_VECTOR (39 downto 0);
    signal tmp_121_i_fu_470_p1 : STD_LOGIC_VECTOR (40 downto 0);
    signal tmp_i2_fu_462_p1 : STD_LOGIC_VECTOR (40 downto 0);
    signal tmp_123_i_fu_501_p3 : STD_LOGIC_VECTOR (61 downto 0);
    signal p_Val2_13_fu_490_p3 : STD_LOGIC_VECTOR (42 downto 0);
    signal tmp_123_i_cast_fu_509_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal tmp_124_i_cast_fu_513_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal p_Val2_14_fu_517_p2 : STD_LOGIC_VECTOR (62 downto 0);
    signal tmp_i3_fu_486_p2 : STD_LOGIC_VECTOR (39 downto 0);
    signal tmp_42_fu_549_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal p_Result_i4_fu_553_p3 : STD_LOGIC_VECTOR (20 downto 0);
    signal tmp_45_fu_575_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_fu_561_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_i_i_i_fu_583_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal qbit_fu_541_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal qb_assign_2_fu_589_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_15_fu_531_p4 : STD_LOGIC_VECTOR (39 downto 0);
    signal tmp_126_i_fu_595_p1 : STD_LOGIC_VECTOR (39 downto 0);
    signal tmp_127_i_fu_613_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_78_i_not_fu_623_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal not_carry_i_fu_628_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal carry_6_fu_618_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal deleted_zeros_6_fu_633_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_not_i_i5_fu_648_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge_i_i10_fu_654_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge40_demorgan_i_1_fu_665_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_demorgan_fu_669_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal overflow_1_fu_659_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge_i_i_i2_fu_680_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp1_fu_693_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_not_i2_fu_697_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_i2_fu_702_p3 : STD_LOGIC_VECTOR (39 downto 0);
    signal tmp_58_fu_729_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_61_fu_765_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_1_fu_733_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_i_i2_fu_773_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal qbit_1_fu_721_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal qb_assign_1_fu_779_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_3_fu_747_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_3_fu_785_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_60_fu_757_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_fu_803_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_9_fu_823_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_Result_1_fu_839_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_63_fu_815_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range2_all_ones_fu_833_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_fu_861_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_41_i_fu_867_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal deleted_ones_fu_873_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal deleted_zeros_fu_887_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_not_i1_fu_896_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge_i2_fu_902_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_7_fu_907_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_38_i_fu_892_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp21_demorgan_fu_918_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp2_fu_923_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_2_fu_929_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal overflow_2_fu_912_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp3_fu_940_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge_i_i2_fu_934_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_1_not_fu_945_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_8_mux_fu_951_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Val2_8_fu_958_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_shl2_fu_981_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_shl3_fu_993_p3 : STD_LOGIC_VECTOR (29 downto 0);
    signal p_shl2_cast_fu_989_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal p_shl3_cast_fu_1001_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal p_Val2_5_fu_1005_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal tmp_64_fu_1011_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_8_fu_1023_p3 : STD_LOGIC_VECTOR (54 downto 0);
    signal p_shl6_fu_1015_p3 : STD_LOGIC_VECTOR (55 downto 0);
    signal p_shl7_fu_1031_p1 : STD_LOGIC_VECTOR (55 downto 0);
    signal r_V_2_fu_1048_p0 : STD_LOGIC_VECTOR (39 downto 0);
    signal OP1_V_fu_1041_p1 : STD_LOGIC_VECTOR (64 downto 0);
    signal r_V_2_fu_1048_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal r_V_3_fu_1058_p0 : STD_LOGIC_VECTOR (39 downto 0);
    signal r_V_3_fu_1058_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal p_Result_s_fu_1080_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal newsignbit_6_fu_1072_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_not_i5_fu_1090_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal isneg_1_fu_1064_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge_i6_fu_1096_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_22_fu_1102_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_not38_i1_fu_1120_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal newsignbit_0_not_i1_fu_1114_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge39_i1_fu_1126_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_6_fu_1132_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal overflow_6_fu_1108_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_5_not_fu_1144_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge_i_i6_fu_1138_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_84_fu_1156_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal brmerge5_fu_1150_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_23_fu_1160_p3 : STD_LOGIC_VECTOR (20 downto 0);
    signal tmp_27_fu_1168_p3 : STD_LOGIC_VECTOR (20 downto 0);
    signal p_Result_2_fu_1200_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal newsignbit_8_fu_1192_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_not_i6_fu_1210_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal isneg_2_fu_1184_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge_i7_fu_1216_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_25_fu_1222_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_not38_i2_fu_1240_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal newsignbit_0_not_i2_fu_1234_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge39_i2_fu_1246_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_8_fu_1252_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal overflow_8_fu_1228_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_6_not_fu_1264_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge_i_i7_fu_1258_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_89_fu_1276_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal brmerge6_fu_1270_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_34_fu_1280_p3 : STD_LOGIC_VECTOR (20 downto 0);
    signal tmp_36_fu_1288_p3 : STD_LOGIC_VECTOR (20 downto 0);
    signal tmp_16_fu_1304_p3 : STD_LOGIC_VECTOR (61 downto 0);
    signal tmp_17_fu_1315_p3 : STD_LOGIC_VECTOR (59 downto 0);
    signal p_shl9_fu_1322_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal p_shl8_fu_1311_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal tmp_67_fu_1358_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal tmp_69_fu_1368_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_2_fu_1362_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_i_i3_fu_1376_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal qbit_2_fu_1350_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal qb_assign_3_fu_1382_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_7_fu_1340_p4 : STD_LOGIC_VECTOR (26 downto 0);
    signal tmp_9_fu_1388_p1 : STD_LOGIC_VECTOR (26 downto 0);
    signal tmp_2_fu_1406_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_10_fu_1422_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_fu_1447_p0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_1456_p0 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_68_fu_1462_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_fu_1469_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal carry_1_fu_1474_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_71_fu_1480_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_11_fu_1493_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_41_i1_fu_1499_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal deleted_zeros_1_fu_1487_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_not_i2_fu_1516_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge_i3_fu_1522_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_12_fu_1527_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal deleted_ones_1_fu_1504_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_38_i1_fu_1511_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge40_demorgan_i_2_fu_1538_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp23_demorgan_fu_1543_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp21_fu_1549_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_3_fu_1555_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal overflow_3_fu_1532_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp22_fu_1566_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge_i_i3_fu_1560_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_2_not_fu_1572_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_13_mux_fu_1578_p3 : STD_LOGIC_VECTOR (26 downto 0);
    signal p_Val2_s_33_fu_1585_p3 : STD_LOGIC_VECTOR (26 downto 0);
    signal tmp_167_i_cast_fu_1613_p1 : STD_LOGIC_VECTOR (38 downto 0);
    signal tmp_168_i_cast_fu_1621_p1 : STD_LOGIC_VECTOR (38 downto 0);
    signal tmp_162_i_cast_fu_1644_p1 : STD_LOGIC_VECTOR (38 downto 0);
    signal tmp_163_i_cast_fu_1652_p1 : STD_LOGIC_VECTOR (38 downto 0);
    signal p_shl4_fu_1680_p3 : STD_LOGIC_VECTOR (46 downto 0);
    signal p_shl5_fu_1691_p3 : STD_LOGIC_VECTOR (44 downto 0);
    signal p_shl4_cast_fu_1687_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal p_shl5_cast_fu_1698_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal p_Val2_25_fu_1711_p1 : STD_LOGIC_VECTOR (38 downto 0);
    signal p_Val2_25_fu_1711_p2 : STD_LOGIC_VECTOR (58 downto 0);
    signal p_Val2_28_fu_1756_p1 : STD_LOGIC_VECTOR (38 downto 0);
    signal p_Val2_28_fu_1756_p2 : STD_LOGIC_VECTOR (58 downto 0);
    signal tmp_20_fu_1798_p4 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_75_fu_1823_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_3_fu_1818_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_i_i4_fu_1830_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal qbit_3_fu_1811_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal qb_assign_5_fu_1836_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_18_fu_1807_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal tmp_14_fu_1842_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal tmp_18_fu_1863_p3 : STD_LOGIC_VECTOR (65 downto 0);
    signal tmp_24_cast_fu_1870_p1 : STD_LOGIC_VECTOR (67 downto 0);
    signal tmp_22_cast_fu_1860_p1 : STD_LOGIC_VECTOR (67 downto 0);
    signal p_Val2_21_fu_1874_p2 : STD_LOGIC_VECTOR (67 downto 0);
    signal tmp_79_fu_1906_p1 : STD_LOGIC_VECTOR (41 downto 0);
    signal tmp_80_fu_1916_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_4_fu_1910_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_i_i5_fu_1924_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal qbit_4_fu_1898_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal qb_assign_7_fu_1930_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_22_fu_1888_p4 : STD_LOGIC_VECTOR (24 downto 0);
    signal tmp_19_fu_1936_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal p_not_i_i_fu_1966_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge_i_i11_fu_1971_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_169_i_fu_1976_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_ones_10_fu_1961_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge40_demorgan_i_5_fu_1987_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge40_i_i_fu_1992_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_7_fu_1998_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal overflow_7_fu_1981_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge_i_i_i_fu_2003_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_26_fu_1954_p3 : STD_LOGIC_VECTOR (51 downto 0);
    signal underflow_not_i_fu_2009_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_118_mux_i_fu_2015_p3 : STD_LOGIC_VECTOR (51 downto 0);
    signal p_Val2_i_fu_2023_p3 : STD_LOGIC_VECTOR (51 downto 0);
    signal p_not_i_i1_fu_2051_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge_i_i12_fu_2056_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_164_i_fu_2061_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_ones_11_fu_2046_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge40_demorgan_i_6_fu_2072_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge40_i_i1_fu_2077_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_9_fu_2083_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal overflow_9_fu_2066_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge_i_i_i1_fu_2088_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_29_fu_2039_p3 : STD_LOGIC_VECTOR (51 downto 0);
    signal underflow_not_i1_fu_2094_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_114_mux_i_fu_2100_p3 : STD_LOGIC_VECTOR (51 downto 0);
    signal p_Val2_i1_fu_2108_p3 : STD_LOGIC_VECTOR (51 downto 0);
    signal tmp_15_fu_2124_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_16_not_fu_2134_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal not_carry_2_fu_2139_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal carry_2_fu_2129_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal deleted_zeros_2_fu_2144_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_not_i3_fu_2154_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge_i4_fu_2160_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal deleted_ones_2_fu_2149_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge40_demorgan_i_3_fu_2171_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp25_demorgan_fu_2176_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp23_fu_2182_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_4_fu_2188_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal overflow_4_fu_2165_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp24_fu_2199_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_21_fu_2211_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal not_carry_3_fu_2226_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal deleted_zeros_3_fu_2231_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_not_i4_fu_2241_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge_i5_fu_2247_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal deleted_ones_3_fu_2236_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp27_demorgan_fu_2263_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp25_fu_2269_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal overflow_5_fu_2252_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_44_fu_2293_p3 : STD_LOGIC_VECTOR (52 downto 0);
    signal p_shl10_fu_2286_p3 : STD_LOGIC_VECTOR (54 downto 0);
    signal p_shl11_fu_2300_p1 : STD_LOGIC_VECTOR (54 downto 0);
    signal brmerge_i_i4_fu_2193_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_3_not_fu_2205_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_46_fu_2310_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal tmp_47_fu_2317_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal tmp_48_fu_2324_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal tmp_49_fu_2347_p3 : STD_LOGIC_VECTOR (52 downto 0);
    signal p_shl12_fu_2340_p3 : STD_LOGIC_VECTOR (54 downto 0);
    signal p_shl13_fu_2354_p1 : STD_LOGIC_VECTOR (54 downto 0);
    signal brmerge_i_i5_fu_2280_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_100_fu_2371_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp26_fu_2381_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_33_cast_fu_2390_p1 : STD_LOGIC_VECTOR (57 downto 0);
    signal tmp_35_cast_fu_2393_p1 : STD_LOGIC_VECTOR (57 downto 0);
    signal p_Val2_31_fu_2396_p2 : STD_LOGIC_VECTOR (57 downto 0);
    signal tmp_94_fu_2428_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_96_fu_2446_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_5_fu_2432_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_i_i6_fu_2454_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal qbit_5_fu_2420_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal qb_assign_9_fu_2460_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_32_fu_2410_p4 : STD_LOGIC_VECTOR (24 downto 0);
    signal tmp_30_fu_2466_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal underflow_4_not_fu_2385_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_51_fu_2487_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal tmp_52_fu_2493_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal tmp_33_fu_2500_p3 : STD_LOGIC_VECTOR (56 downto 0);
    signal tmp_44_cast_fu_2508_p1 : STD_LOGIC_VECTOR (57 downto 0);
    signal tmp_42_cast_fu_2484_p1 : STD_LOGIC_VECTOR (57 downto 0);
    signal p_Val2_35_fu_2512_p2 : STD_LOGIC_VECTOR (57 downto 0);
    signal tmp_102_fu_2551_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_i_i7_fu_2559_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal qbit_6_fu_2536_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal qb_assign_6_fu_2564_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_36_fu_2526_p4 : STD_LOGIC_VECTOR (24 downto 0);
    signal tmp_35_fu_2570_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal tmp_37_fu_2588_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal carry_5_fu_2594_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_31_fu_2606_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_32_not_fu_2616_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal not_carry_4_fu_2621_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal carry_4_fu_2611_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal deleted_zeros_4_fu_2626_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_not_i7_fu_2641_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge_i8_fu_2647_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_32_fu_2631_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_38_i4_fu_2636_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge40_demorgan_i_7_fu_2658_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp29_demorgan_fu_2662_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_10_fu_2668_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal overflow_10_fu_2652_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp30_fu_2679_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge_i_i8_fu_2673_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_7_not_fu_2684_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_30_mux_fu_2690_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal p_Val2_6_35_fu_2697_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal p_Result_39_not_fu_2712_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal not_carry_5_fu_2717_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal deleted_zeros_5_fu_2722_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_not_i8_fu_2732_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge_i9_fu_2738_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_38_fu_2727_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge40_demorgan_i_8_fu_2749_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp31_demorgan_fu_2753_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_11_fu_2758_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal overflow_11_fu_2743_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp32_fu_2769_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge_i_i9_fu_2763_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_8_not_fu_2774_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_35_mux_fu_2779_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal p_Val2_7_36_fu_2786_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal p_Val2_38_fu_2793_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal tmp_39_fu_2801_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal p_Val2_39_fu_2805_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal newsignbit_12_fu_2823_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal isneg_3_fu_2811_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_41_fu_2831_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal isneg_3_not_fu_2849_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge_i_i_fu_2843_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_40_fu_2819_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal underflow_12_fu_2837_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge9_fu_2855_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_38_mux_fu_2861_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal p_Val2_9_37_fu_2869_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (19 downto 0);

    component dqo_2_abc IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        d_V : IN STD_LOGIC_VECTOR (24 downto 0);
        q_V : IN STD_LOGIC_VECTOR (24 downto 0);
        theta_V : IN STD_LOGIC_VECTOR (15 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (24 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (24 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (24 downto 0) );
    end component;


    component abc_2_dqo IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        a_V : IN STD_LOGIC_VECTOR (24 downto 0);
        b_V : IN STD_LOGIC_VECTOR (24 downto 0);
        c_V : IN STD_LOGIC_VECTOR (24 downto 0);
        theta_V : IN STD_LOGIC_VECTOR (15 downto 0);
        Is_d_V : OUT STD_LOGIC_VECTOR (24 downto 0);
        Is_d_V_ap_vld : OUT STD_LOGIC;
        Is_q_V : OUT STD_LOGIC_VECTOR (24 downto 0);
        Is_q_V_ap_vld : OUT STD_LOGIC );
    end component;


    component pmsm_mul_4ns_65s_jbC IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (3 downto 0);
        din1 : IN STD_LOGIC_VECTOR (64 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (66 downto 0) );
    end component;



begin
    grp_dqo_2_abc_fu_284 : component dqo_2_abc
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_dqo_2_abc_fu_284_ap_start,
        ap_done => grp_dqo_2_abc_fu_284_ap_done,
        ap_idle => grp_dqo_2_abc_fu_284_ap_idle,
        ap_ready => grp_dqo_2_abc_fu_284_ap_ready,
        d_V => p_s_reg_3385,
        q_V => this_assign_6_1_reg_3390,
        theta_V => this_assign_s_reg_3041,
        ap_return_0 => grp_dqo_2_abc_fu_284_ap_return_0,
        ap_return_1 => grp_dqo_2_abc_fu_284_ap_return_1,
        ap_return_2 => grp_dqo_2_abc_fu_284_ap_return_2);

    grp_abc_2_dqo_fu_293 : component abc_2_dqo
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_abc_2_dqo_fu_293_ap_start,
        ap_done => grp_abc_2_dqo_fu_293_ap_done,
        ap_idle => grp_abc_2_dqo_fu_293_ap_idle,
        ap_ready => grp_abc_2_dqo_fu_293_ap_ready,
        a_V => Is_a_V,
        b_V => Is_b_V,
        c_V => Is_c_V,
        theta_V => this_assign_s_reg_3041,
        Is_d_V => grp_abc_2_dqo_fu_293_Is_d_V,
        Is_d_V_ap_vld => grp_abc_2_dqo_fu_293_Is_d_V_ap_vld,
        Is_q_V => grp_abc_2_dqo_fu_293_Is_q_V,
        Is_q_V_ap_vld => grp_abc_2_dqo_fu_293_Is_q_V_ap_vld);

    pmsm_mul_4ns_65s_jbC_U38 : component pmsm_mul_4ns_65s_jbC
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 4,
        din1_WIDTH => 65,
        dout_WIDTH => 67)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_1447_p0,
        din1 => r_V_2_reg_3068,
        ce => ap_const_logic_1,
        dout => grp_fu_1447_p2);

    pmsm_mul_4ns_65s_jbC_U39 : component pmsm_mul_4ns_65s_jbC
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 4,
        din1_WIDTH => 65,
        dout_WIDTH => 67)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_1456_p0,
        din1 => r_V_3_reg_3073,
        ce => ap_const_logic_1,
        dout => grp_fu_1456_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_reg_grp_abc_2_dqo_fu_293_ap_start_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_grp_abc_2_dqo_fu_293_ap_start <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
                    ap_reg_grp_abc_2_dqo_fu_293_ap_start <= ap_const_logic_1;
                elsif ((grp_abc_2_dqo_fu_293_ap_ready = ap_const_logic_1)) then 
                    ap_reg_grp_abc_2_dqo_fu_293_ap_start <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_reg_grp_dqo_2_abc_fu_284_ap_start_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_grp_dqo_2_abc_fu_284_ap_start <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state19)) then 
                    ap_reg_grp_dqo_2_abc_fu_284_ap_start <= ap_const_logic_1;
                elsif ((grp_dqo_2_abc_fu_284_ap_ready = ap_const_logic_1)) then 
                    ap_reg_grp_dqo_2_abc_fu_284_ap_start <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state8) and (grp_abc_2_dqo_fu_293_Is_d_V_ap_vld = ap_const_logic_1))) then
                Is_d_V <= grp_abc_2_dqo_fu_293_Is_d_V;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state15)) then
                Is_d_dif_V_load_reg_3264 <= Is_d_dif_V_load_fu_2031_p3;
                agg_result_V_i_reg_3270 <= agg_result_V_i_fu_2116_p3;
                newsignbit_4_reg_3233 <= p_Val2_19_fu_1846_p2(24 downto 24);
                newsignbit_5_reg_3256 <= p_Val2_23_fu_1940_p2(24 downto 24);
                p_Val2_19_reg_3227 <= p_Val2_19_fu_1846_p2;
                p_Val2_23_reg_3250 <= p_Val2_23_fu_1940_p2;
                signbit_4_reg_3241 <= p_Val2_21_fu_1874_p2(67 downto 67);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state8) and (grp_abc_2_dqo_fu_293_Is_q_V_ap_vld = ap_const_logic_1))) then
                Is_q_V <= grp_abc_2_dqo_fu_293_Is_q_V;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state10)) then
                Range1_all_ones_1_reg_3118 <= Range1_all_ones_1_fu_1432_p2;
                Range1_all_zeros_1_reg_3125 <= Range1_all_zeros_1_fu_1438_p2;
                Range2_all_ones_1_reg_3113 <= Range2_all_ones_1_fu_1416_p2;
                newsignbit_3_reg_3106 <= p_Val2_8_32_fu_1392_p2(26 downto 26);
                    p_Val2_6_reg_3088(62 downto 31) <= p_Val2_6_fu_1326_p2(62 downto 31);
                p_Val2_8_32_reg_3100 <= p_Val2_8_32_fu_1392_p2;
                signbit_2_reg_3094 <= p_Val2_6_fu_1326_p2(62 downto 62);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                Range1_all_ones_reg_3024 <= Range1_all_ones_fu_849_p2;
                Range1_all_zeros_reg_3030 <= Range1_all_zeros_fu_855_p2;
                brmerge40_demorgan_i_reg_3035 <= brmerge40_demorgan_i_fu_881_p2;
                carry_reg_3018 <= carry_fu_809_p2;
                newsignbit_2_reg_3013 <= p_Val2_4_fu_789_p2(15 downto 15);
                out_ant_V <= p_Val2_17_fu_708_p3;
                p_Val2_4_reg_3007 <= p_Val2_4_fu_789_p2;
                signbit_1_reg_3001 <= p_Val2_17_fu_708_p3(39 downto 39);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state16)) then
                brmerge40_demorgan_i_4_reg_3286 <= brmerge40_demorgan_i_4_fu_2258_p2;
                carry_3_reg_3276 <= carry_3_fu_2216_p2;
                p_Result_23_not_reg_3281 <= p_Result_23_not_fu_2221_p2;
                    p_Val2_30_reg_3296(54 downto 1) <= p_Val2_30_fu_2304_p2(54 downto 1);
                    p_Val2_34_reg_3306(54 downto 1) <= p_Val2_34_fu_2358_p2(54 downto 1);
                r_6_reg_3317 <= r_6_fu_2375_p2;
                    tmp_28_reg_3301(56 downto 32) <= tmp_28_fu_2332_p3(56 downto 32);
                tmp_50_reg_3312 <= tmp_50_fu_2364_p3;
                underflow_5_reg_3291 <= underflow_5_fu_2275_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state13)) then
                    in_ant_V(37 downto 17) <= tmp_167_i_fu_1606_p3(37 downto 17);
                    in_ant_V_3(37 downto 17) <= tmp_162_i_fu_1637_p3(37 downto 17);
                    r_V_4_reg_3140(38 downto 17) <= r_V_4_fu_1625_p2(38 downto 17);
                    r_V_5_reg_3145(38 downto 17) <= r_V_5_fu_1656_p2(38 downto 17);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                in_ant_V_2 <= p_Val2_10_fu_454_p3;
                p_Val2_10_reg_2933 <= p_Val2_10_fu_454_p3;
                p_Val2_11_reg_2941 <= in_ant_V_2;
                r_V_reg_2946 <= r_V_fu_474_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state17)) then
                newsignbit_10_reg_3343 <= p_Val2_33_fu_2470_p2(24 downto 24);
                newsignbit_11_reg_3371 <= p_Val2_37_fu_2574_p2(24 downto 24);
                p_38_i5_reg_3379 <= p_38_i5_fu_2600_p2;
                p_Val2_33_reg_3337 <= p_Val2_33_fu_2470_p2;
                p_Val2_37_reg_3365 <= p_Val2_37_fu_2574_p2;
                signbit_7_reg_3322 <= p_Val2_31_fu_2396_p2(57 downto 57);
                signbit_8_reg_3352 <= p_Val2_35_fu_2512_p2(57 downto 57);
                tmp_101_reg_3360 <= p_Val2_35_fu_2512_p2(56 downto 56);
                tmp_95_reg_3331 <= p_Val2_31_fu_2396_p2(56 downto 56);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                newsignbit_1_reg_2972 <= p_Val2_16_fu_599_p2(39 downto 39);
                p_Val2_16_reg_2966 <= p_Val2_16_fu_599_p2;
                signbit_reg_2951 <= p_Val2_14_fu_517_p2(62 downto 62);
                tmp_43_reg_2960 <= p_Val2_14_fu_517_p2(61 downto 61);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state14)) then
                newsignbit_7_reg_3187 <= p_Val2_25_fu_1711_p2(52 downto 52);
                newsignbit_9_reg_3210 <= p_Val2_28_fu_1756_p2(52 downto 52);
                    p_Val2_20_reg_3176(47 downto 5) <= p_Val2_20_fu_1702_p2(47 downto 5);
                p_Val2_2_34_reg_3171 <= grp_fu_1456_p2;
                p_Val2_9_reg_3150 <= grp_fu_1447_p2;
                signbit_3_reg_3157 <= grp_fu_1447_p2(66 downto 66);
                signbit_5_reg_3181 <= p_Val2_25_fu_1711_p2(58 downto 58);
                signbit_6_reg_3204 <= p_Val2_28_fu_1756_p2(58 downto 58);
                tmp_24_reg_3198 <= p_Val2_25_fu_1711_p2(58 downto 53);
                tmp_26_reg_3221 <= p_Val2_28_fu_1756_p2(58 downto 53);
                tmp_74_reg_3166 <= tmp_74_fu_1676_p1;
                tmp_i1_reg_3216 <= p_Val2_28_fu_1756_p2(52 downto 2);
                tmp_i_reg_3193 <= p_Val2_25_fu_1711_p2(52 downto 2);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                overflow_reg_2920 <= overflow_fu_388_p2;
                    tmp_reg_2915(23 downto 5) <= tmp_fu_348_p1(23 downto 5);
                underflow_reg_2926 <= underflow_fu_412_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                p_38_i_i_reg_2986 <= p_38_i_i_fu_643_p2;
                p_Val2_89_mux_i_reg_2996 <= p_Val2_89_mux_i_fu_686_p3;
                tmp_128_i_reg_2981 <= tmp_128_i_fu_638_p2;
                underflow_1_reg_2991 <= underflow_1_fu_675_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state18)) then
                p_s_reg_3385 <= p_s_fu_2704_p3;
                this_assign_6_1_reg_3390 <= this_assign_6_1_fu_2877_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state9)) then
                    r_V_1_reg_3062(55 downto 27) <= r_V_1_fu_1035_p2(55 downto 27);
                r_V_2_reg_3068 <= r_V_2_fu_1048_p2;
                r_V_3_reg_3073 <= r_V_3_fu_1058_p2;
                tmp_29_reg_3078 <= tmp_29_fu_1176_p3;
                tmp_40_reg_3083 <= tmp_40_fu_1296_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                this_assign_s_reg_3041 <= this_assign_s_fu_965_p3;
            end if;
        end if;
    end process;
    in_ant_V(16 downto 0) <= "00000000000000000";
    in_ant_V_3(16 downto 0) <= "00000000000000000";
    tmp_reg_2915(4 downto 0) <= "00000";
    r_V_1_reg_3062(26 downto 0) <= "000000000000000000000000000";
    p_Val2_6_reg_3088(30 downto 0) <= "0000000000000000000000000000000";
    r_V_4_reg_3140(16 downto 0) <= "00000000000000000";
    r_V_5_reg_3145(16 downto 0) <= "00000000000000000";
    p_Val2_20_reg_3176(4 downto 0) <= "00000";
    p_Val2_30_reg_3296(0) <= '0';
    tmp_28_reg_3301(31 downto 0) <= "00000000000000000000000000000000";
    p_Val2_34_reg_3306(0) <= '0';

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_dqo_2_abc_fu_284_ap_done, grp_abc_2_dqo_fu_293_ap_done, ap_CS_fsm_state20, ap_CS_fsm_state8)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                if (((grp_abc_2_dqo_fu_293_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state16;
            when ap_ST_fsm_state16 => 
                ap_NS_fsm <= ap_ST_fsm_state17;
            when ap_ST_fsm_state17 => 
                ap_NS_fsm <= ap_ST_fsm_state18;
            when ap_ST_fsm_state18 => 
                ap_NS_fsm <= ap_ST_fsm_state19;
            when ap_ST_fsm_state19 => 
                ap_NS_fsm <= ap_ST_fsm_state20;
            when ap_ST_fsm_state20 => 
                if (((grp_dqo_2_abc_fu_284_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state20))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state20;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXXXXX";
        end case;
    end process;
    Fem_a_V <= grp_dqo_2_abc_fu_284_ap_return_0;

    Fem_a_V_ap_vld_assign_proc : process(grp_dqo_2_abc_fu_284_ap_done, ap_CS_fsm_state20)
    begin
        if (((grp_dqo_2_abc_fu_284_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state20))) then 
            Fem_a_V_ap_vld <= ap_const_logic_1;
        else 
            Fem_a_V_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    Fem_b_V <= grp_dqo_2_abc_fu_284_ap_return_1;

    Fem_b_V_ap_vld_assign_proc : process(grp_dqo_2_abc_fu_284_ap_done, ap_CS_fsm_state20)
    begin
        if (((grp_dqo_2_abc_fu_284_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state20))) then 
            Fem_b_V_ap_vld <= ap_const_logic_1;
        else 
            Fem_b_V_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    Fem_c_V <= grp_dqo_2_abc_fu_284_ap_return_2;

    Fem_c_V_ap_vld_assign_proc : process(grp_dqo_2_abc_fu_284_ap_done, ap_CS_fsm_state20)
    begin
        if (((grp_dqo_2_abc_fu_284_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state20))) then 
            Fem_c_V_ap_vld <= ap_const_logic_1;
        else 
            Fem_c_V_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    Is_d_dif_V_load_fu_2031_p3 <= 
        p_Val2_118_mux_i_fu_2015_p3 when (underflow_not_i_fu_2009_p2(0) = '1') else 
        p_Val2_i_fu_2023_p3;
        OP1_V_fu_1041_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Val2_10_reg_2933),65));

    Range1_all_ones_10_fu_1961_p2 <= "1" when (tmp_24_reg_3198 = ap_const_lv6_3F) else "0";
    Range1_all_ones_11_fu_2046_p2 <= "1" when (tmp_26_reg_3221 = ap_const_lv6_3F) else "0";
    Range1_all_ones_1_fu_1432_p2 <= "1" when (tmp_10_fu_1422_p4 = ap_const_lv5_1F) else "0";
    Range1_all_ones_fu_849_p2 <= "1" when (p_Result_1_fu_839_p4 = ap_const_lv5_1F) else "0";
    Range1_all_zeros_1_fu_1438_p2 <= "1" when (tmp_10_fu_1422_p4 = ap_const_lv5_0) else "0";
    Range1_all_zeros_fu_855_p2 <= "1" when (p_Result_1_fu_839_p4 = ap_const_lv5_0) else "0";
    Range2_all_ones_1_fu_1416_p2 <= "1" when (tmp_2_fu_1406_p4 = ap_const_lv4_F) else "0";
    Range2_all_ones_fu_833_p2 <= "1" when (p_Result_9_fu_823_p4 = ap_const_lv4_F) else "0";
    Tem_aux_V <= 
        p_Val2_13_mux_fu_1578_p3 when (underflow_2_not_fu_1572_p2(0) = '1') else 
        p_Val2_s_33_fu_1585_p3;

    Tem_aux_V_ap_vld_assign_proc : process(ap_CS_fsm_state11)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            Tem_aux_V_ap_vld <= ap_const_logic_1;
        else 
            Tem_aux_V_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    agg_result_V_i_fu_2116_p3 <= 
        p_Val2_114_mux_i_fu_2100_p3 when (underflow_not_i1_fu_2094_p2(0) = '1') else 
        p_Val2_i1_fu_2108_p3;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state14 <= ap_CS_fsm(13);
    ap_CS_fsm_state15 <= ap_CS_fsm(14);
    ap_CS_fsm_state16 <= ap_CS_fsm(15);
    ap_CS_fsm_state17 <= ap_CS_fsm(16);
    ap_CS_fsm_state18 <= ap_CS_fsm(17);
    ap_CS_fsm_state19 <= ap_CS_fsm(18);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state20 <= ap_CS_fsm(19);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, grp_dqo_2_abc_fu_284_ap_done, ap_CS_fsm_state20)
    begin
        if ((((grp_dqo_2_abc_fu_284_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state20)) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_dqo_2_abc_fu_284_ap_done, ap_CS_fsm_state20)
    begin
        if (((grp_dqo_2_abc_fu_284_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state20))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    brmerge39_i1_fu_1126_p2 <= (p_not38_i1_fu_1120_p2 or newsignbit_0_not_i1_fu_1114_p2);
    brmerge39_i2_fu_1246_p2 <= (p_not38_i2_fu_1240_p2 or newsignbit_0_not_i2_fu_1234_p2);
    brmerge39_i_fu_406_p2 <= (p_not38_i_fu_400_p2 or newsignbit_0_not_i_fu_394_p2);
    brmerge40_demorgan_i_1_fu_665_p2 <= (signbit_reg_2951 and newsignbit_1_reg_2972);
    brmerge40_demorgan_i_2_fu_1538_p2 <= (newsignbit_3_reg_3106 and deleted_ones_1_fu_1504_p3);
    brmerge40_demorgan_i_3_fu_2171_p2 <= (newsignbit_4_reg_3233 and deleted_ones_2_fu_2149_p2);
    brmerge40_demorgan_i_4_fu_2258_p2 <= (newsignbit_5_reg_3256 and deleted_ones_3_fu_2236_p2);
    brmerge40_demorgan_i_5_fu_1987_p2 <= (newsignbit_7_reg_3187 and Range1_all_ones_10_fu_1961_p2);
    brmerge40_demorgan_i_6_fu_2072_p2 <= (newsignbit_9_reg_3210 and Range1_all_ones_11_fu_2046_p2);
    brmerge40_demorgan_i_7_fu_2658_p2 <= (signbit_7_reg_3322 and newsignbit_10_reg_3343);
    brmerge40_demorgan_i_8_fu_2749_p2 <= (signbit_8_reg_3352 and newsignbit_11_reg_3371);
    brmerge40_demorgan_i_fu_881_p2 <= (newsignbit_2_fu_795_p3 and deleted_ones_fu_873_p3);
    brmerge40_i_i1_fu_2077_p2 <= (brmerge40_demorgan_i_6_fu_2072_p2 xor ap_const_lv1_1);
    brmerge40_i_i_fu_1992_p2 <= (brmerge40_demorgan_i_5_fu_1987_p2 xor ap_const_lv1_1);
    brmerge5_fu_1150_p2 <= (underflow_5_not_fu_1144_p2 or overflow_6_fu_1108_p2);
    brmerge6_fu_1270_p2 <= (underflow_6_not_fu_1264_p2 or overflow_8_fu_1228_p2);
    brmerge9_fu_2855_p2 <= (newsignbit_12_fu_2823_p3 or isneg_3_not_fu_2849_p2);
    brmerge_fu_434_p2 <= (underflow_not_fu_429_p2 or overflow_reg_2920);
    brmerge_i1_fu_376_p2 <= (p_not_i_fu_370_p2 or newsignbit_fu_352_p3);
    brmerge_i2_fu_902_p2 <= (p_not_i1_fu_896_p2 or newsignbit_2_reg_3013);
    brmerge_i3_fu_1522_p2 <= (p_not_i2_fu_1516_p2 or newsignbit_3_reg_3106);
    brmerge_i4_fu_2160_p2 <= (p_not_i3_fu_2154_p2 or newsignbit_4_reg_3233);
    brmerge_i5_fu_2247_p2 <= (p_not_i4_fu_2241_p2 or newsignbit_5_reg_3256);
    brmerge_i6_fu_1096_p2 <= (p_not_i5_fu_1090_p2 or newsignbit_6_fu_1072_p3);
    brmerge_i7_fu_1216_p2 <= (p_not_i6_fu_1210_p2 or newsignbit_8_fu_1192_p3);
    brmerge_i8_fu_2647_p2 <= (p_not_i7_fu_2641_p2 or newsignbit_10_reg_3343);
    brmerge_i9_fu_2738_p2 <= (p_not_i8_fu_2732_p2 or newsignbit_11_reg_3371);
    brmerge_i_i10_fu_654_p2 <= (p_not_i_i5_fu_648_p2 or newsignbit_1_reg_2972);
    brmerge_i_i11_fu_1971_p2 <= (p_not_i_i_fu_1966_p2 or newsignbit_7_reg_3187);
    brmerge_i_i12_fu_2056_p2 <= (p_not_i_i1_fu_2051_p2 or newsignbit_9_reg_3210);
    brmerge_i_i1_fu_425_p2 <= (underflow_reg_2926 or overflow_reg_2920);
    brmerge_i_i2_fu_934_p2 <= (underflow_2_fu_929_p2 or overflow_2_fu_912_p2);
    brmerge_i_i3_fu_1560_p2 <= (underflow_3_fu_1555_p2 or overflow_3_fu_1532_p2);
    brmerge_i_i4_fu_2193_p2 <= (underflow_4_fu_2188_p2 or overflow_4_fu_2165_p2);
    brmerge_i_i5_fu_2280_p2 <= (underflow_5_fu_2275_p2 or overflow_5_fu_2252_p2);
    brmerge_i_i6_fu_1138_p2 <= (underflow_6_fu_1132_p2 or overflow_6_fu_1108_p2);
    brmerge_i_i7_fu_1258_p2 <= (underflow_8_fu_1252_p2 or overflow_8_fu_1228_p2);
    brmerge_i_i8_fu_2673_p2 <= (underflow_10_fu_2668_p2 or overflow_10_fu_2652_p2);
    brmerge_i_i9_fu_2763_p2 <= (underflow_11_fu_2758_p2 or overflow_11_fu_2743_p2);
    brmerge_i_i_fu_2843_p2 <= (newsignbit_12_fu_2823_p3 xor isneg_3_fu_2811_p3);
    brmerge_i_i_i1_fu_2088_p2 <= (underflow_9_fu_2083_p2 or overflow_9_fu_2066_p2);
    brmerge_i_i_i2_fu_680_p2 <= (underflow_1_fu_675_p2 or overflow_1_fu_659_p2);
    brmerge_i_i_i_fu_2003_p2 <= (underflow_7_fu_1998_p2 or overflow_7_fu_1981_p2);
    carry_1_fu_1474_p2 <= (tmp_s_fu_1469_p2 and tmp_68_fu_1462_p3);
    carry_2_fu_2129_p2 <= (tmp_15_fu_2124_p2 and signbit_3_reg_3157);
    carry_3_fu_2216_p2 <= (tmp_21_fu_2211_p2 and signbit_4_reg_3241);
    carry_4_fu_2611_p2 <= (tmp_95_reg_3331 and tmp_31_fu_2606_p2);
    carry_5_fu_2594_p2 <= (tmp_37_fu_2588_p2 and tmp_101_fu_2543_p3);
    carry_6_fu_618_p2 <= (tmp_43_reg_2960 and tmp_127_i_fu_613_p2);
    carry_fu_809_p2 <= (tmp_60_fu_757_p3 and tmp_4_fu_803_p2);
    deleted_ones_1_fu_1504_p3 <= 
        p_41_i1_fu_1499_p2 when (carry_1_fu_1474_p2(0) = '1') else 
        Range1_all_ones_1_reg_3118;
    deleted_ones_2_fu_2149_p2 <= (signbit_3_reg_3157 xor carry_2_fu_2129_p2);
    deleted_ones_3_fu_2236_p2 <= (signbit_4_reg_3241 xor carry_3_fu_2216_p2);
    deleted_ones_fu_873_p3 <= 
        p_41_i_fu_867_p2 when (carry_fu_809_p2(0) = '1') else 
        Range1_all_ones_fu_849_p2;
    deleted_zeros_1_fu_1487_p3 <= 
        Range1_all_ones_1_reg_3118 when (carry_1_fu_1474_p2(0) = '1') else 
        Range1_all_zeros_1_reg_3125;
    deleted_zeros_2_fu_2144_p2 <= (signbit_3_reg_3157 xor not_carry_2_fu_2139_p2);
    deleted_zeros_3_fu_2231_p2 <= (signbit_4_reg_3241 xor not_carry_3_fu_2226_p2);
    deleted_zeros_4_fu_2626_p2 <= (signbit_7_reg_3322 xor not_carry_4_fu_2621_p2);
    deleted_zeros_5_fu_2722_p2 <= (signbit_8_reg_3352 xor not_carry_5_fu_2717_p2);
    deleted_zeros_6_fu_633_p2 <= (signbit_reg_2951 xor not_carry_i_fu_628_p2);
    deleted_zeros_fu_887_p3 <= 
        Range1_all_ones_reg_3024 when (carry_reg_3018(0) = '1') else 
        Range1_all_zeros_reg_3030;
    grp_abc_2_dqo_fu_293_ap_start <= ap_reg_grp_abc_2_dqo_fu_293_ap_start;
    grp_dqo_2_abc_fu_284_ap_start <= ap_reg_grp_dqo_2_abc_fu_284_ap_start;
    grp_fu_1447_p0 <= ap_const_lv67_6(4 - 1 downto 0);
    grp_fu_1456_p0 <= ap_const_lv67_6(4 - 1 downto 0);
    isneg_1_fu_1064_p3 <= Is_d_V(24 downto 24);
    isneg_2_fu_1184_p3 <= Is_q_V(24 downto 24);
    isneg_3_fu_2811_p3 <= p_Val2_39_fu_2805_p2(25 downto 25);
    isneg_3_not_fu_2849_p2 <= (isneg_3_fu_2811_p3 xor ap_const_lv1_1);
    isneg_fu_340_p3 <= p_Val2_s_fu_334_p2(32 downto 32);
    newsignbit_0_not_i1_fu_1114_p2 <= (newsignbit_6_fu_1072_p3 xor ap_const_lv1_1);
    newsignbit_0_not_i2_fu_1234_p2 <= (newsignbit_8_fu_1192_p3 xor ap_const_lv1_1);
    newsignbit_0_not_i_fu_394_p2 <= (newsignbit_fu_352_p3 xor ap_const_lv1_1);
    newsignbit_11_fu_2580_p3 <= p_Val2_37_fu_2574_p2(24 downto 24);
    newsignbit_12_fu_2823_p3 <= p_Val2_39_fu_2805_p2(24 downto 24);
    newsignbit_2_fu_795_p3 <= p_Val2_4_fu_789_p2(15 downto 15);
    newsignbit_6_fu_1072_p3 <= Is_d_V(20 downto 20);
    newsignbit_8_fu_1192_p3 <= Is_q_V(20 downto 20);
    newsignbit_fu_352_p3 <= p_Val2_s_fu_334_p2(23 downto 23);
    not_carry_2_fu_2139_p2 <= (p_Result_16_not_fu_2134_p2 or newsignbit_4_reg_3233);
    not_carry_3_fu_2226_p2 <= (p_Result_23_not_fu_2221_p2 or newsignbit_5_reg_3256);
    not_carry_4_fu_2621_p2 <= (p_Result_32_not_fu_2616_p2 or newsignbit_10_reg_3343);
    not_carry_5_fu_2717_p2 <= (p_Result_39_not_fu_2712_p2 or newsignbit_11_reg_3371);
    not_carry_i_fu_628_p2 <= (p_Result_78_i_not_fu_623_p2 or newsignbit_1_reg_2972);
    overflow_10_fu_2652_p2 <= (tmp_32_fu_2631_p2 and brmerge_i8_fu_2647_p2);
    overflow_11_fu_2743_p2 <= (tmp_38_fu_2727_p2 and brmerge_i9_fu_2738_p2);
    overflow_1_fu_659_p2 <= (tmp_128_i_fu_638_p2 and brmerge_i_i10_fu_654_p2);
    overflow_2_fu_912_p2 <= (tmp_7_fu_907_p2 and brmerge_i2_fu_902_p2);
    overflow_3_fu_1532_p2 <= (tmp_12_fu_1527_p2 and brmerge_i3_fu_1522_p2);
    overflow_4_fu_2165_p2 <= (p_Result_16_not_fu_2134_p2 and brmerge_i4_fu_2160_p2);
    overflow_5_fu_2252_p2 <= (p_Result_23_not_fu_2221_p2 and brmerge_i5_fu_2247_p2);
    overflow_6_fu_1108_p2 <= (tmp_22_fu_1102_p2 and brmerge_i6_fu_1096_p2);
    overflow_7_fu_1981_p2 <= (tmp_169_i_fu_1976_p2 and brmerge_i_i11_fu_1971_p2);
    overflow_8_fu_1228_p2 <= (tmp_25_fu_1222_p2 and brmerge_i7_fu_1216_p2);
    overflow_9_fu_2066_p2 <= (tmp_164_i_fu_2061_p2 and brmerge_i_i12_fu_2056_p2);
    overflow_fu_388_p2 <= (tmp_1_fu_382_p2 and brmerge_i1_fu_376_p2);
    p_38_i1_fu_1511_p2 <= (carry_1_fu_1474_p2 and Range1_all_ones_1_reg_3118);
    p_38_i4_fu_2636_p2 <= (signbit_7_reg_3322 and carry_4_fu_2611_p2);
    p_38_i5_fu_2600_p2 <= (signbit_8_fu_2518_p3 and carry_5_fu_2594_p2);
    p_38_i_fu_892_p2 <= (carry_reg_3018 and Range1_all_ones_reg_3024);
    p_38_i_i_fu_643_p2 <= (signbit_reg_2951 and carry_6_fu_618_p2);
    p_41_i1_fu_1499_p2 <= (tmp_11_fu_1493_p2 and Range2_all_ones_1_reg_3113);
    p_41_i_fu_867_p2 <= (tmp_5_fu_861_p2 and Range2_all_ones_fu_833_p2);
    p_Result_16_not_fu_2134_p2 <= (signbit_3_reg_3157 xor ap_const_lv1_1);
    p_Result_1_fu_839_p4 <= p_Val2_17_fu_708_p3(39 downto 35);
    p_Result_23_not_fu_2221_p2 <= (signbit_4_reg_3241 xor ap_const_lv1_1);
    p_Result_2_fu_1200_p4 <= Is_q_V(24 downto 21);
    p_Result_32_not_fu_2616_p2 <= (tmp_95_reg_3331 xor ap_const_lv1_1);
    p_Result_39_not_fu_2712_p2 <= (tmp_101_reg_3360 xor ap_const_lv1_1);
    p_Result_78_i_not_fu_623_p2 <= (tmp_43_reg_2960 xor ap_const_lv1_1);
    p_Result_9_fu_823_p4 <= p_Val2_17_fu_708_p3(39 downto 36);
    p_Result_i4_fu_553_p3 <= (tmp_42_fu_549_p1 & ap_const_lv2_0);
    p_Result_s_fu_1080_p4 <= Is_d_V(24 downto 21);
    p_Val2_10_fu_454_p3 <= 
        p_Val2_2_mux_fu_439_p3 when (brmerge_fu_434_p2(0) = '1') else 
        p_Val2_2_fu_447_p3;
    p_Val2_114_mux_i_fu_2100_p3 <= 
        ap_const_lv52_7FFFFFFFFFFFF when (brmerge_i_i_i1_fu_2088_p2(0) = '1') else 
        p_Val2_29_fu_2039_p3;
    p_Val2_118_mux_i_fu_2015_p3 <= 
        ap_const_lv52_7FFFFFFFFFFFF when (brmerge_i_i_i_fu_2003_p2(0) = '1') else 
        p_Val2_26_fu_1954_p3;
    p_Val2_13_fu_490_p3 <= (r_V_reg_2946 & ap_const_lv2_0);
    p_Val2_13_mux_fu_1578_p3 <= 
        ap_const_lv27_3FFFFFF when (brmerge_i_i3_fu_1560_p2(0) = '1') else 
        p_Val2_8_32_reg_3100;
    p_Val2_14_fu_517_p2 <= std_logic_vector(signed(tmp_123_i_cast_fu_509_p1) + signed(tmp_124_i_cast_fu_513_p1));
    p_Val2_15_fu_531_p4 <= p_Val2_14_fu_517_p2(61 downto 22);
    p_Val2_16_fu_599_p2 <= std_logic_vector(unsigned(p_Val2_15_fu_531_p4) + unsigned(tmp_126_i_fu_595_p1));
    p_Val2_17_fu_708_p3 <= 
        p_Val2_89_mux_i_reg_2996 when (underflow_not_i2_fu_697_p2(0) = '1') else 
        p_Val2_i2_fu_702_p3;
        p_Val2_18_fu_1807_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_20_fu_1798_p4),25));

    p_Val2_19_fu_1846_p2 <= std_logic_vector(signed(p_Val2_18_fu_1807_p1) + signed(tmp_14_fu_1842_p1));
    p_Val2_1_fu_418_p3 <= (tmp_reg_2915 & ap_const_lv16_0);
    p_Val2_20_fu_1702_p2 <= std_logic_vector(signed(p_shl4_cast_fu_1687_p1) + signed(p_shl5_cast_fu_1698_p1));
    p_Val2_21_fu_1874_p2 <= std_logic_vector(signed(tmp_24_cast_fu_1870_p1) + signed(tmp_22_cast_fu_1860_p1));
    p_Val2_22_fu_1888_p4 <= p_Val2_21_fu_1874_p2(67 downto 43);
    p_Val2_23_fu_1940_p2 <= std_logic_vector(unsigned(p_Val2_22_fu_1888_p4) + unsigned(tmp_19_fu_1936_p1));
    p_Val2_25_fu_1711_p1 <= r_V_4_reg_3140;
    p_Val2_25_fu_1711_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed('0' &ap_const_lv59_F4240) * signed(p_Val2_25_fu_1711_p1))), 59));
    p_Val2_26_fu_1954_p3 <= (tmp_i_reg_3193 & ap_const_lv1_0);
    p_Val2_28_fu_1756_p1 <= r_V_5_reg_3145;
    p_Val2_28_fu_1756_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed('0' &ap_const_lv59_F4240) * signed(p_Val2_28_fu_1756_p1))), 59));
    p_Val2_29_fu_2039_p3 <= (tmp_i1_reg_3216 & ap_const_lv1_0);
    p_Val2_2_fu_447_p3 <= 
        ap_const_lv40_8000000000 when (underflow_reg_2926(0) = '1') else 
        p_Val2_1_fu_418_p3;
    p_Val2_2_mux_fu_439_p3 <= 
        ap_const_lv40_7FFFFFFFFF when (brmerge_i_i1_fu_425_p2(0) = '1') else 
        p_Val2_1_fu_418_p3;
    p_Val2_30_fu_2304_p2 <= std_logic_vector(unsigned(p_shl10_fu_2286_p3) - unsigned(p_shl11_fu_2300_p1));
    p_Val2_30_mux_fu_2690_p3 <= 
        ap_const_lv25_FFFFFF when (brmerge_i_i8_fu_2673_p2(0) = '1') else 
        p_Val2_33_reg_3337;
    p_Val2_31_fu_2396_p2 <= std_logic_vector(signed(tmp_33_cast_fu_2390_p1) - signed(tmp_35_cast_fu_2393_p1));
    p_Val2_32_fu_2410_p4 <= p_Val2_31_fu_2396_p2(56 downto 32);
    p_Val2_33_fu_2470_p2 <= std_logic_vector(unsigned(p_Val2_32_fu_2410_p4) + unsigned(tmp_30_fu_2466_p1));
    p_Val2_34_fu_2358_p2 <= std_logic_vector(unsigned(p_shl12_fu_2340_p3) - unsigned(p_shl13_fu_2354_p1));
    p_Val2_35_fu_2512_p2 <= std_logic_vector(signed(tmp_44_cast_fu_2508_p1) + signed(tmp_42_cast_fu_2484_p1));
    p_Val2_35_mux_fu_2779_p3 <= 
        ap_const_lv25_FFFFFF when (brmerge_i_i9_fu_2763_p2(0) = '1') else 
        p_Val2_37_reg_3365;
    p_Val2_36_fu_2526_p4 <= p_Val2_35_fu_2512_p2(56 downto 32);
    p_Val2_37_fu_2574_p2 <= std_logic_vector(unsigned(p_Val2_36_fu_2526_p4) + unsigned(tmp_35_fu_2570_p1));
    p_Val2_38_fu_2793_p3 <= 
        p_Val2_35_mux_fu_2779_p3 when (underflow_8_not_fu_2774_p2(0) = '1') else 
        p_Val2_7_36_fu_2786_p3;
    p_Val2_38_mux_fu_2861_p3 <= 
        ap_const_lv25_FFFFFF when (brmerge_i_i_fu_2843_p2(0) = '1') else 
        p_Val2_40_fu_2819_p1;
    p_Val2_39_fu_2805_p2 <= std_logic_vector(unsigned(ap_const_lv26_0) - unsigned(tmp_39_fu_2801_p1));
    p_Val2_3_fu_747_p4 <= p_Val2_17_fu_708_p3(34 downto 19);
    p_Val2_40_fu_2819_p1 <= p_Val2_39_fu_2805_p2(25 - 1 downto 0);
    p_Val2_4_fu_789_p2 <= std_logic_vector(unsigned(p_Val2_3_fu_747_p4) + unsigned(tmp_3_fu_785_p1));
    p_Val2_5_fu_1005_p2 <= std_logic_vector(signed(p_shl2_cast_fu_989_p1) + signed(p_shl3_cast_fu_1001_p1));
    p_Val2_6_35_fu_2697_p3 <= 
        ap_const_lv25_1000000 when (underflow_10_fu_2668_p2(0) = '1') else 
        p_Val2_33_reg_3337;
    p_Val2_6_fu_1326_p2 <= std_logic_vector(signed(p_shl9_fu_1322_p1) + signed(p_shl8_fu_1311_p1));
    p_Val2_7_36_fu_2786_p3 <= 
        ap_const_lv25_1000000 when (underflow_11_fu_2758_p2(0) = '1') else 
        p_Val2_37_reg_3365;
    p_Val2_7_fu_1340_p4 <= p_Val2_6_fu_1326_p2(57 downto 31);
    p_Val2_89_mux_i_fu_686_p3 <= 
        ap_const_lv40_7FFFFFFFFF when (brmerge_i_i_i2_fu_680_p2(0) = '1') else 
        p_Val2_16_reg_2966;
    p_Val2_8_32_fu_1392_p2 <= std_logic_vector(unsigned(p_Val2_7_fu_1340_p4) + unsigned(tmp_9_fu_1388_p1));
    p_Val2_8_fu_958_p3 <= 
        ap_const_lv16_8000 when (underflow_2_fu_929_p2(0) = '1') else 
        p_Val2_4_reg_3007;
    p_Val2_8_mux_fu_951_p3 <= 
        ap_const_lv16_7FFF when (brmerge_i_i2_fu_934_p2(0) = '1') else 
        p_Val2_4_reg_3007;
    p_Val2_9_37_fu_2869_p3 <= 
        ap_const_lv25_1000000 when (underflow_12_fu_2837_p2(0) = '1') else 
        p_Val2_40_fu_2819_p1;
    p_Val2_i1_fu_2108_p3 <= 
        ap_const_lv52_8000000000000 when (underflow_9_fu_2083_p2(0) = '1') else 
        p_Val2_29_fu_2039_p3;
    p_Val2_i2_fu_702_p3 <= 
        ap_const_lv40_8000000000 when (underflow_1_reg_2991(0) = '1') else 
        p_Val2_16_reg_2966;
    p_Val2_i_fu_2023_p3 <= 
        ap_const_lv52_8000000000000 when (underflow_7_fu_1998_p2(0) = '1') else 
        p_Val2_26_fu_1954_p3;
    p_Val2_s_33_fu_1585_p3 <= 
        ap_const_lv27_4000000 when (underflow_3_fu_1555_p2(0) = '1') else 
        p_Val2_8_32_reg_3100;
    p_Val2_s_fu_334_p2 <= std_logic_vector(signed(p_shl1_cast_fu_330_p1) + signed(p_shl_cast_fu_318_p1));
    p_not38_i1_fu_1120_p2 <= "0" when (p_Result_s_fu_1080_p4 = ap_const_lv4_F) else "1";
    p_not38_i2_fu_1240_p2 <= "0" when (p_Result_2_fu_1200_p4 = ap_const_lv4_F) else "1";
    p_not38_i_fu_400_p2 <= "0" when (tmp_6_fu_360_p4 = ap_const_lv9_1FF) else "1";
    p_not_i1_fu_896_p2 <= (deleted_zeros_fu_887_p3 xor ap_const_lv1_1);
    p_not_i2_fu_1516_p2 <= (deleted_zeros_1_fu_1487_p3 xor ap_const_lv1_1);
    p_not_i3_fu_2154_p2 <= (deleted_zeros_2_fu_2144_p2 xor ap_const_lv1_1);
    p_not_i4_fu_2241_p2 <= (deleted_zeros_3_fu_2231_p2 xor ap_const_lv1_1);
    p_not_i5_fu_1090_p2 <= "0" when (p_Result_s_fu_1080_p4 = ap_const_lv4_0) else "1";
    p_not_i6_fu_1210_p2 <= "0" when (p_Result_2_fu_1200_p4 = ap_const_lv4_0) else "1";
    p_not_i7_fu_2641_p2 <= (deleted_zeros_4_fu_2626_p2 xor ap_const_lv1_1);
    p_not_i8_fu_2732_p2 <= (deleted_zeros_5_fu_2722_p2 xor ap_const_lv1_1);
    p_not_i_fu_370_p2 <= "0" when (tmp_6_fu_360_p4 = ap_const_lv9_0) else "1";
    p_not_i_i1_fu_2051_p2 <= "0" when (tmp_26_reg_3221 = ap_const_lv6_0) else "1";
    p_not_i_i5_fu_648_p2 <= (deleted_zeros_6_fu_633_p2 xor ap_const_lv1_1);
    p_not_i_i_fu_1966_p2 <= "0" when (tmp_24_reg_3198 = ap_const_lv6_0) else "1";
    p_s_fu_2704_p3 <= 
        p_Val2_30_mux_fu_2690_p3 when (underflow_7_not_fu_2684_p2(0) = '1') else 
        p_Val2_6_35_fu_2697_p3;
    p_shl10_fu_2286_p3 <= (Is_d_dif_V_load_reg_3264 & ap_const_lv3_0);
        p_shl11_fu_2300_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_44_fu_2293_p3),55));

    p_shl12_fu_2340_p3 <= (agg_result_V_i_reg_3270 & ap_const_lv3_0);
        p_shl13_fu_2354_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_49_fu_2347_p3),55));

        p_shl1_cast_fu_330_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_shl1_fu_322_p3),33));

    p_shl1_fu_322_p3 <= (Wn_o_V & ap_const_lv5_0);
        p_shl2_cast_fu_989_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_shl2_fu_981_p3),33));

    p_shl2_fu_981_p3 <= (Is_q_V & ap_const_lv7_0);
        p_shl3_cast_fu_1001_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_shl3_fu_993_p3),33));

    p_shl3_fu_993_p3 <= (Is_q_V & ap_const_lv5_0);
        p_shl4_cast_fu_1687_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_shl4_fu_1680_p3),48));

    p_shl4_fu_1680_p3 <= (p_Val2_10_reg_2933 & ap_const_lv7_0);
        p_shl5_cast_fu_1698_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_shl5_fu_1691_p3),48));

    p_shl5_fu_1691_p3 <= (p_Val2_10_reg_2933 & ap_const_lv5_0);
    p_shl6_fu_1015_p3 <= (tmp_64_fu_1011_p1 & ap_const_lv24_0);
        p_shl7_fu_1031_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_8_fu_1023_p3),56));

        p_shl8_fu_1311_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_16_fu_1304_p3),63));

        p_shl9_fu_1322_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_17_fu_1315_p3),63));

        p_shl_cast_fu_318_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_shl_fu_310_p3),33));

    p_shl_fu_310_p3 <= (Wn_o_V & ap_const_lv7_0);
    qb_assign_1_fu_779_p2 <= (r_i_i2_fu_773_p2 and qbit_1_fu_721_p3);
    qb_assign_2_fu_589_p2 <= (r_i_i_i_fu_583_p2 and qbit_fu_541_p3);
    qb_assign_3_fu_1382_p2 <= (r_i_i3_fu_1376_p2 and qbit_2_fu_1350_p3);
    qb_assign_5_fu_1836_p2 <= (r_i_i4_fu_1830_p2 and qbit_3_fu_1811_p3);
    qb_assign_6_fu_2564_p2 <= (r_i_i7_fu_2559_p2 and qbit_6_fu_2536_p3);
    qb_assign_7_fu_1930_p2 <= (r_i_i5_fu_1924_p2 and qbit_4_fu_1898_p3);
    qb_assign_9_fu_2460_p2 <= (r_i_i6_fu_2454_p2 and qbit_5_fu_2420_p3);
    qbit_1_fu_721_p3 <= p_Val2_17_fu_708_p3(18 downto 18);
    qbit_2_fu_1350_p3 <= p_Val2_6_fu_1326_p2(30 downto 30);
    qbit_3_fu_1811_p3 <= p_Val2_9_reg_3150(42 downto 42);
    qbit_4_fu_1898_p3 <= p_Val2_21_fu_1874_p2(42 downto 42);
    qbit_5_fu_2420_p3 <= p_Val2_31_fu_2396_p2(31 downto 31);
    qbit_6_fu_2536_p3 <= p_Val2_34_reg_3306(31 downto 31);
    qbit_fu_541_p3 <= tmp_i3_fu_486_p2(19 downto 19);
    r_1_fu_733_p2 <= "0" when (tmp_58_fu_729_p1 = ap_const_lv18_0) else "1";
    r_2_fu_1362_p2 <= "0" when (tmp_67_fu_1358_p1 = ap_const_lv30_0) else "1";
    r_3_fu_1818_p2 <= "0" when (tmp_74_reg_3166 = ap_const_lv42_0) else "1";
    r_4_fu_1910_p2 <= "0" when (tmp_79_fu_1906_p1 = ap_const_lv42_0) else "1";
    r_5_fu_2432_p2 <= "0" when (tmp_94_fu_2428_p1 = ap_const_lv31_0) else "1";
    r_6_fu_2375_p2 <= "0" when (tmp_100_fu_2371_p1 = ap_const_lv31_0) else "1";
    r_V_1_fu_1035_p2 <= std_logic_vector(unsigned(p_shl6_fu_1015_p3) - unsigned(p_shl7_fu_1031_p1));
    r_V_2_fu_1048_p0 <= OP1_V_fu_1041_p1(40 - 1 downto 0);
    r_V_2_fu_1048_p1 <= Is_q_V;
    r_V_2_fu_1048_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(r_V_2_fu_1048_p0) * signed(r_V_2_fu_1048_p1))), 65));
    r_V_3_fu_1058_p0 <= OP1_V_fu_1041_p1(40 - 1 downto 0);
    r_V_3_fu_1058_p1 <= Is_d_V;
    r_V_3_fu_1058_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(r_V_3_fu_1058_p0) * signed(r_V_3_fu_1058_p1))), 65));
    r_V_4_fu_1625_p2 <= std_logic_vector(signed(tmp_167_i_cast_fu_1613_p1) - signed(tmp_168_i_cast_fu_1621_p1));
    r_V_5_fu_1656_p2 <= std_logic_vector(signed(tmp_162_i_cast_fu_1644_p1) - signed(tmp_163_i_cast_fu_1652_p1));
    r_V_fu_474_p2 <= std_logic_vector(signed(tmp_121_i_fu_470_p1) + signed(tmp_i2_fu_462_p1));
    r_fu_561_p2 <= "0" when (p_Result_i4_fu_553_p3 = ap_const_lv21_0) else "1";
    r_i_i2_fu_773_p2 <= (tmp_61_fu_765_p3 or r_1_fu_733_p2);
    r_i_i3_fu_1376_p2 <= (tmp_69_fu_1368_p3 or r_2_fu_1362_p2);
    r_i_i4_fu_1830_p2 <= (tmp_75_fu_1823_p3 or r_3_fu_1818_p2);
    r_i_i5_fu_1924_p2 <= (tmp_80_fu_1916_p3 or r_4_fu_1910_p2);
    r_i_i6_fu_2454_p2 <= (tmp_96_fu_2446_p3 or r_5_fu_2432_p2);
    r_i_i7_fu_2559_p2 <= (tmp_102_fu_2551_p3 or r_6_reg_3317);
    r_i_i_i_fu_583_p2 <= (tmp_45_fu_575_p3 or r_fu_561_p2);
    signbit_8_fu_2518_p3 <= p_Val2_35_fu_2512_p2(57 downto 57);
    this_assign_6_1_fu_2877_p3 <= 
        p_Val2_38_mux_fu_2861_p3 when (brmerge9_fu_2855_p2(0) = '1') else 
        p_Val2_9_37_fu_2869_p3;
    this_assign_s_fu_965_p3 <= 
        p_Val2_8_mux_fu_951_p3 when (underflow_1_not_fu_945_p2(0) = '1') else 
        p_Val2_8_fu_958_p3;
    tmp1_fu_693_p2 <= (tmp_128_i_reg_2981 or newsignbit_1_reg_2972);
    tmp21_demorgan_fu_918_p2 <= (p_38_i_fu_892_p2 or brmerge40_demorgan_i_reg_3035);
    tmp21_fu_1549_p2 <= (tmp23_demorgan_fu_1543_p2 xor ap_const_lv1_1);
    tmp22_fu_1566_p2 <= (tmp_12_fu_1527_p2 or brmerge40_demorgan_i_2_fu_1538_p2);
    tmp23_demorgan_fu_1543_p2 <= (p_38_i1_fu_1511_p2 or brmerge40_demorgan_i_2_fu_1538_p2);
    tmp23_fu_2182_p2 <= (tmp25_demorgan_fu_2176_p2 xor ap_const_lv1_1);
    tmp24_fu_2199_p2 <= (p_Result_16_not_fu_2134_p2 or brmerge40_demorgan_i_3_fu_2171_p2);
    tmp25_demorgan_fu_2176_p2 <= (carry_2_fu_2129_p2 or brmerge40_demorgan_i_3_fu_2171_p2);
    tmp25_fu_2269_p2 <= (tmp27_demorgan_fu_2263_p2 xor ap_const_lv1_1);
    tmp26_fu_2381_p2 <= (p_Result_23_not_reg_3281 or brmerge40_demorgan_i_4_reg_3286);
    tmp27_demorgan_fu_2263_p2 <= (carry_3_fu_2216_p2 or brmerge40_demorgan_i_4_fu_2258_p2);
    tmp29_demorgan_fu_2662_p2 <= (p_38_i4_fu_2636_p2 or brmerge40_demorgan_i_7_fu_2658_p2);
    tmp2_fu_923_p2 <= (tmp21_demorgan_fu_918_p2 xor ap_const_lv1_1);
    tmp30_fu_2679_p2 <= (tmp_32_fu_2631_p2 or newsignbit_10_reg_3343);
    tmp31_demorgan_fu_2753_p2 <= (p_38_i5_reg_3379 or brmerge40_demorgan_i_8_fu_2749_p2);
    tmp32_fu_2769_p2 <= (tmp_38_fu_2727_p2 or newsignbit_11_reg_3371);
    tmp3_fu_940_p2 <= (tmp_7_fu_907_p2 or brmerge40_demorgan_i_reg_3035);
    tmp_100_fu_2371_p1 <= p_Val2_34_fu_2358_p2(31 - 1 downto 0);
    tmp_101_fu_2543_p3 <= p_Val2_35_fu_2512_p2(56 downto 56);
    tmp_102_fu_2551_p3 <= p_Val2_35_fu_2512_p2(32 downto 32);
    tmp_10_fu_1422_p4 <= p_Val2_6_fu_1326_p2(62 downto 58);
    tmp_11_fu_1493_p2 <= (tmp_71_fu_1480_p3 xor ap_const_lv1_1);
        tmp_121_i_fu_470_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(in_ant_V_2),41));

        tmp_123_i_cast_fu_509_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_123_i_fu_501_p3),63));

    tmp_123_i_fu_501_p3 <= (out_ant_V & ap_const_lv22_0);
        tmp_124_i_cast_fu_513_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Val2_13_fu_490_p3),63));

    tmp_126_i_fu_595_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(qb_assign_2_fu_589_p2),40));
    tmp_127_i_fu_613_p2 <= (newsignbit_1_reg_2972 xor ap_const_lv1_1);
    tmp_128_i_fu_638_p2 <= (signbit_reg_2951 xor ap_const_lv1_1);
    tmp_12_fu_1527_p2 <= (signbit_2_reg_3094 xor ap_const_lv1_1);
    tmp_14_fu_1842_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(qb_assign_5_fu_1836_p2),25));
    tmp_15_fu_2124_p2 <= (newsignbit_4_reg_3233 xor ap_const_lv1_1);
        tmp_162_i_cast_fu_1644_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_162_i_fu_1637_p3),39));

    tmp_162_i_fu_1637_p3 <= (tmp_40_reg_3083 & ap_const_lv17_0);
        tmp_163_i_cast_fu_1652_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(in_ant_V_3),39));

    tmp_164_i_fu_2061_p2 <= (signbit_6_reg_3204 xor ap_const_lv1_1);
        tmp_167_i_cast_fu_1613_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_167_i_fu_1606_p3),39));

    tmp_167_i_fu_1606_p3 <= (tmp_29_reg_3078 & ap_const_lv17_0);
        tmp_168_i_cast_fu_1621_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(in_ant_V),39));

    tmp_169_i_fu_1976_p2 <= (signbit_5_reg_3181 xor ap_const_lv1_1);
    tmp_16_fu_1304_p3 <= (r_V_1_reg_3062 & ap_const_lv6_0);
    tmp_17_fu_1315_p3 <= (r_V_1_reg_3062 & ap_const_lv4_0);
    tmp_18_fu_1863_p3 <= (p_Val2_20_reg_3176 & ap_const_lv18_0);
    tmp_19_fu_1936_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(qb_assign_7_fu_1930_p2),25));
    tmp_1_fu_382_p2 <= (isneg_fu_340_p3 xor ap_const_lv1_1);
    tmp_20_fu_1798_p4 <= p_Val2_9_reg_3150(66 downto 43);
    tmp_21_fu_2211_p2 <= (newsignbit_5_reg_3256 xor ap_const_lv1_1);
        tmp_22_cast_fu_1860_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Val2_2_34_reg_3171),68));

    tmp_22_fu_1102_p2 <= (isneg_1_fu_1064_p3 xor ap_const_lv1_1);
    tmp_23_fu_1160_p3 <= 
        ap_const_lv21_FFFFF when (brmerge_i_i6_fu_1138_p2(0) = '1') else 
        tmp_84_fu_1156_p1;
        tmp_24_cast_fu_1870_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_18_fu_1863_p3),68));

    tmp_25_fu_1222_p2 <= (isneg_2_fu_1184_p3 xor ap_const_lv1_1);
    tmp_27_fu_1168_p3 <= 
        ap_const_lv21_100000 when (underflow_6_fu_1132_p2(0) = '1') else 
        tmp_84_fu_1156_p1;
    tmp_28_fu_2332_p3 <= (tmp_48_fu_2324_p3 & ap_const_lv32_0);
    tmp_29_fu_1176_p3 <= 
        tmp_23_fu_1160_p3 when (brmerge5_fu_1150_p2(0) = '1') else 
        tmp_27_fu_1168_p3;
    tmp_2_fu_1406_p4 <= p_Val2_6_fu_1326_p2(62 downto 59);
    tmp_30_fu_2466_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(qb_assign_9_fu_2460_p2),25));
    tmp_31_fu_2606_p2 <= (newsignbit_10_reg_3343 xor ap_const_lv1_1);
    tmp_32_fu_2631_p2 <= (signbit_7_reg_3322 xor ap_const_lv1_1);
        tmp_33_cast_fu_2390_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Val2_30_reg_3296),58));

    tmp_33_fu_2500_p3 <= (tmp_52_fu_2493_p3 & ap_const_lv32_0);
    tmp_34_fu_1280_p3 <= 
        ap_const_lv21_FFFFF when (brmerge_i_i7_fu_1258_p2(0) = '1') else 
        tmp_89_fu_1276_p1;
        tmp_35_cast_fu_2393_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_28_reg_3301),58));

    tmp_35_fu_2570_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(qb_assign_6_fu_2564_p2),25));
    tmp_36_fu_1288_p3 <= 
        ap_const_lv21_100000 when (underflow_8_fu_1252_p2(0) = '1') else 
        tmp_89_fu_1276_p1;
    tmp_37_fu_2588_p2 <= (newsignbit_11_fu_2580_p3 xor ap_const_lv1_1);
    tmp_38_fu_2727_p2 <= (signbit_8_reg_3352 xor ap_const_lv1_1);
        tmp_39_fu_2801_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Val2_38_fu_2793_p3),26));

    tmp_3_fu_785_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(qb_assign_1_fu_779_p2),16));
    tmp_40_fu_1296_p3 <= 
        tmp_34_fu_1280_p3 when (brmerge6_fu_1270_p2(0) = '1') else 
        tmp_36_fu_1288_p3;
    tmp_41_fu_2831_p2 <= (newsignbit_12_fu_2823_p3 xor ap_const_lv1_1);
        tmp_42_cast_fu_2484_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Val2_34_reg_3306),58));

    tmp_42_fu_549_p1 <= tmp_i3_fu_486_p2(19 - 1 downto 0);
        tmp_44_cast_fu_2508_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_33_fu_2500_p3),58));

    tmp_44_fu_2293_p3 <= (Is_d_dif_V_load_reg_3264 & ap_const_lv1_0);
    tmp_45_fu_575_p3 <= p_Val2_14_fu_517_p2(22 downto 22);
    tmp_46_fu_2310_p3 <= 
        ap_const_lv25_FFFFFF when (brmerge_i_i4_fu_2193_p2(0) = '1') else 
        p_Val2_19_reg_3227;
    tmp_47_fu_2317_p3 <= 
        ap_const_lv25_1000000 when (underflow_4_fu_2188_p2(0) = '1') else 
        p_Val2_19_reg_3227;
    tmp_48_fu_2324_p3 <= 
        tmp_46_fu_2310_p3 when (underflow_3_not_fu_2205_p2(0) = '1') else 
        tmp_47_fu_2317_p3;
    tmp_49_fu_2347_p3 <= (agg_result_V_i_reg_3270 & ap_const_lv1_0);
    tmp_4_fu_803_p2 <= (newsignbit_2_fu_795_p3 xor ap_const_lv1_1);
    tmp_50_fu_2364_p3 <= 
        ap_const_lv25_FFFFFF when (brmerge_i_i5_fu_2280_p2(0) = '1') else 
        p_Val2_23_reg_3250;
    tmp_51_fu_2487_p3 <= 
        ap_const_lv25_1000000 when (underflow_5_reg_3291(0) = '1') else 
        p_Val2_23_reg_3250;
    tmp_52_fu_2493_p3 <= 
        tmp_50_reg_3312 when (underflow_4_not_fu_2385_p2(0) = '1') else 
        tmp_51_fu_2487_p3;
    tmp_58_fu_729_p1 <= p_Val2_17_fu_708_p3(18 - 1 downto 0);
    tmp_5_fu_861_p2 <= (tmp_63_fu_815_p3 xor ap_const_lv1_1);
    tmp_60_fu_757_p3 <= p_Val2_17_fu_708_p3(34 downto 34);
    tmp_61_fu_765_p3 <= p_Val2_17_fu_708_p3(19 downto 19);
    tmp_63_fu_815_p3 <= p_Val2_17_fu_708_p3(35 downto 35);
    tmp_64_fu_1011_p1 <= p_Val2_5_fu_1005_p2(32 - 1 downto 0);
    tmp_67_fu_1358_p1 <= p_Val2_6_fu_1326_p2(30 - 1 downto 0);
    tmp_68_fu_1462_p3 <= p_Val2_6_reg_3088(57 downto 57);
    tmp_69_fu_1368_p3 <= p_Val2_6_fu_1326_p2(31 downto 31);
    tmp_6_fu_360_p4 <= p_Val2_s_fu_334_p2(32 downto 24);
    tmp_71_fu_1480_p3 <= p_Val2_6_reg_3088(58 downto 58);
    tmp_74_fu_1676_p1 <= grp_fu_1447_p2(42 - 1 downto 0);
    tmp_75_fu_1823_p3 <= p_Val2_9_reg_3150(43 downto 43);
    tmp_79_fu_1906_p1 <= p_Val2_21_fu_1874_p2(42 - 1 downto 0);
    tmp_7_fu_907_p2 <= (signbit_1_reg_3001 xor ap_const_lv1_1);
    tmp_80_fu_1916_p3 <= p_Val2_21_fu_1874_p2(43 downto 43);
    tmp_84_fu_1156_p1 <= Is_d_V(21 - 1 downto 0);
    tmp_89_fu_1276_p1 <= Is_q_V(21 - 1 downto 0);
    tmp_8_fu_1023_p3 <= (p_Val2_5_fu_1005_p2 & ap_const_lv22_0);
    tmp_94_fu_2428_p1 <= p_Val2_31_fu_2396_p2(31 - 1 downto 0);
    tmp_96_fu_2446_p3 <= p_Val2_31_fu_2396_p2(32 downto 32);
    tmp_9_fu_1388_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(qb_assign_3_fu_1382_p2),27));
    tmp_demorgan_fu_669_p2 <= (p_38_i_i_fu_643_p2 or brmerge40_demorgan_i_1_fu_665_p2);
    tmp_fu_348_p1 <= p_Val2_s_fu_334_p2(24 - 1 downto 0);
        tmp_i2_fu_462_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Val2_10_fu_454_p3),41));

    tmp_i3_fu_486_p2 <= std_logic_vector(unsigned(p_Val2_11_reg_2941) + unsigned(p_Val2_10_reg_2933));
    tmp_s_fu_1469_p2 <= (newsignbit_3_reg_3106 xor ap_const_lv1_1);
    underflow_10_fu_2668_p2 <= (tmp29_demorgan_fu_2662_p2 xor signbit_7_reg_3322);
    underflow_11_fu_2758_p2 <= (tmp31_demorgan_fu_2753_p2 xor signbit_8_reg_3352);
    underflow_12_fu_2837_p2 <= (tmp_41_fu_2831_p2 and isneg_3_fu_2811_p3);
    underflow_1_fu_675_p2 <= (tmp_demorgan_fu_669_p2 xor signbit_reg_2951);
    underflow_1_not_fu_945_p2 <= (tmp3_fu_940_p2 or p_38_i_fu_892_p2);
    underflow_2_fu_929_p2 <= (tmp2_fu_923_p2 and signbit_1_reg_3001);
    underflow_2_not_fu_1572_p2 <= (tmp22_fu_1566_p2 or p_38_i1_fu_1511_p2);
    underflow_3_fu_1555_p2 <= (tmp21_fu_1549_p2 and signbit_2_reg_3094);
    underflow_3_not_fu_2205_p2 <= (tmp24_fu_2199_p2 or carry_2_fu_2129_p2);
    underflow_4_fu_2188_p2 <= (tmp23_fu_2182_p2 and signbit_3_reg_3157);
    underflow_4_not_fu_2385_p2 <= (tmp26_fu_2381_p2 or carry_3_reg_3276);
    underflow_5_fu_2275_p2 <= (tmp25_fu_2269_p2 and signbit_4_reg_3241);
    underflow_5_not_fu_1144_p2 <= (underflow_6_fu_1132_p2 xor ap_const_lv1_1);
    underflow_6_fu_1132_p2 <= (isneg_1_fu_1064_p3 and brmerge39_i1_fu_1126_p2);
    underflow_6_not_fu_1264_p2 <= (underflow_8_fu_1252_p2 xor ap_const_lv1_1);
    underflow_7_fu_1998_p2 <= (signbit_5_reg_3181 and brmerge40_i_i_fu_1992_p2);
    underflow_7_not_fu_2684_p2 <= (tmp30_fu_2679_p2 or p_38_i4_fu_2636_p2);
    underflow_8_fu_1252_p2 <= (isneg_2_fu_1184_p3 and brmerge39_i2_fu_1246_p2);
    underflow_8_not_fu_2774_p2 <= (tmp32_fu_2769_p2 or p_38_i5_reg_3379);
    underflow_9_fu_2083_p2 <= (signbit_6_reg_3204 and brmerge40_i_i1_fu_2077_p2);
    underflow_fu_412_p2 <= (isneg_fu_340_p3 and brmerge39_i_fu_406_p2);
    underflow_not_fu_429_p2 <= (underflow_reg_2926 xor ap_const_lv1_1);
    underflow_not_i1_fu_2094_p2 <= (tmp_164_i_fu_2061_p2 or brmerge40_demorgan_i_6_fu_2072_p2);
    underflow_not_i2_fu_697_p2 <= (tmp1_fu_693_p2 or p_38_i_i_reg_2986);
    underflow_not_i_fu_2009_p2 <= (tmp_169_i_fu_1976_p2 or brmerge40_demorgan_i_5_fu_1987_p2);
end behav;
